<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Pooja Rajendran Raju">

<title>Global Dietary Trends</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Global Dietary Trends</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Pooja Rajendran Raju </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load raw data from targets</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>raw_data <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(raw_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This report focuses on the analysis of daily caloric supply derived from carbohydrates, protein, and fat across multiple countries from 1961 to the most recent available year 2022. The objective is to examine global dietary patterns over time, identify regional differences in macronutrient consumption, and explore trends in protein intake from animal-based and plant-based sources.</p>
<section id="data" class="level4">
<h4 class="anchored" data-anchor-id="data">Data</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Glimpse of data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(raw_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 12,877
Columns: 7
$ Entity                                                          &lt;chr&gt; "Afgha…
$ Code                                                            &lt;chr&gt; "AFG",…
$ Year                                                            &lt;int&gt; 1961, …
$ Daily.calorie.supply.per.person.that.comes.from.animal.protein  &lt;dbl&gt; 52.592…
$ Daily.calorie.supply.per.person.that.comes.from.vegetal.protein &lt;dbl&gt; 277.46…
$ Daily.calorie.supply.per.person.from.fat                        &lt;dbl&gt; 328.06…
$ Daily.calorie.supply.per.person.from.carbohydrates              &lt;dbl&gt; 2256.2…</code></pre>
</div>
</div>
<p>Our World in Data is an online platform that provides accessible and comprehensive data on global development issues. The following dataset is used from the platform for analysis:</p>
<p><a href="https://ourworldindata.org/grapher/daily-caloric-supply-derived-from-carbohydrates-protein-and-fat?tab=table&amp;time=earliest">Daily caloric supply derived from carbohydrates, protein and fat</a>: The dataset, provided by Our World in Data, is sourced from the Food and Agriculture Organization (FAO) of the United Nations. It documents the average daily caloric supply per person derived from three primary macronutrients, carbohydrates, protein, and fat, for numerous countries and regions globally. The data spans several decades, offering valuable insights into nutritional trends and shifts over time.</p>
<ul>
<li><strong>Source</strong>: Our World in Data – Daily Caloric Supply Derived from Carbohydrates, Protein, and Fat</li>
<li><strong>Data Provider</strong>: Food and Agriculture Organization (FAO), United Nations</li>
<li><strong>License</strong>: Creative Commons Attribution 4.0 International License (CC BY 4.0), which allows for sharing and adaptation with proper credit.</li>
<li><strong>Data Collection</strong>: Data is collected annually and reflects national food supply estimates, providing an overview of average caloric intake per person per day.</li>
</ul>
</section>
<section id="caloric_supply-dataset-structure" class="level4">
<h4 class="anchored" data-anchor-id="caloric_supply-dataset-structure"><em>caloric_supply</em> Dataset Structure</h4>
<p>The dataset consists of the following columns:</p>
<ul>
<li><strong>Entity</strong>: The name of the country or region. Code The ISO 3166-1 alpha-3 country code.</li>
<li><strong>Year</strong>: The year of the data observation.</li>
<li><strong>Animal Protein (kcal/person/day)</strong>: Daily per capita caloric supply from animal-based proteins.</li>
<li><strong>Vegetal Protein (kcal/person/day)</strong>: Daily per capita caloric supply from plant-based proteins.</li>
<li><strong>Fat (kcal/person/day)</strong>: Daily per capita caloric supply from fats.</li>
<li><strong>Carbohydrates (kcal/person/day)</strong>: Daily per capita caloric supply from carbohydrates.</li>
</ul>
<p>Each row represents the average daily caloric intake for a specific country and year, broken down by macronutrient type.</p>
</section>
<section id="data-limitations" class="level4">
<h4 class="anchored" data-anchor-id="data-limitations">Data Limitations</h4>
<p>While the dataset provides comprehensive coverage of global dietary patterns, there are some limitations to consider:</p>
<ul>
<li><strong>Missing Country Codes</strong>: Some regions or combined areas (e.g., “Africa,” “Asia”) do not have ISO country codes, which may affect regional analyses.</li>
<li><strong>Supply vs.&nbsp;Consumption</strong>: The data represents the food supply rather than actual consumption, as it does not account for food waste, loss during transport, or spoilage.</li>
<li><strong>Annual Aggregation</strong>: The dataset provides annual averages, which do not capture seasonal dietary changes.</li>
<li><strong>Limited Protein Breakdown</strong>: The data only distinguishes between animal-based and plant-based protein sources, without further granularity (e.g., beef vs.&nbsp;chicken for animal protein, or grains vs.&nbsp;legumes for vegetal protein).</li>
<li><strong>Lack of Micronutrient Data</strong>: Vitamins, minerals, and other micronutrients are not represented in this dataset.</li>
</ul>
</section>
</section>
<section id="data-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling">Data Wrangling</h2>
<section id="renaming-variables" class="level4">
<h4 class="anchored" data-anchor-id="renaming-variables">Renaming Variables</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load renamed data</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>renamed_data <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(renamed_data)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display structure</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(renamed_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 12,877
Columns: 7
$ Country         &lt;chr&gt; "Afghanistan", "Afghanistan", "Afghanistan", "Afghanis…
$ Code            &lt;chr&gt; "AFG", "AFG", "AFG", "AFG", "AFG", "AFG", "AFG", "AFG"…
$ Year            &lt;int&gt; 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, …
$ Animal_Protein  &lt;dbl&gt; 52.59264, 52.41573, 55.23608, 55.75903, 58.14664, 62.7…
$ Vegetal_Protein &lt;dbl&gt; 277.4622, 270.2443, 244.7503, 269.1064, 268.2374, 245.…
$ Fat             &lt;dbl&gt; 328.0627, 329.0468, 337.5722, 341.0036, 347.9166, 349.…
$ Carbohydrates   &lt;dbl&gt; 2256.246, 2183.914, 1986.155, 2206.713, 2201.896, 2005…</code></pre>
</div>
</div>
</section>
<section id="missing-value-analysis" class="level4">
<h4 class="anchored" data-anchor-id="missing-value-analysis">Missing Value Analysis</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Load trimmed data</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>trimmed_data <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(trimmed_data)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert empty strings to NA</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>converted_data <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(converted_data)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Detect missing values</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>missing_values <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(missing_values)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Display missing value count</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>missing_values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        Country            Code            Year  Animal_Protein Vegetal_Protein 
              0            2661               0               0               0 
            Fat   Carbohydrates 
              0               0 </code></pre>
</div>
</div>
<ul>
<li>In the entire dataset only variable <code>Code</code> has missing values.<br>
</li>
<li>It currently has 2661 missing codes, which is 4.5% of the total dataset.</li>
</ul>
</section>
<section id="evaluating-and-handling-missing-values" class="level4">
<h4 class="anchored" data-anchor-id="evaluating-and-handling-missing-values">Evaluating and Handling Missing values</h4>
<ul>
<li>After evaluating the missing values in the dataset, we can see that only column <code>Code</code> has missing values. The missing values are primarily associated with <code>Country</code> column, which contains regions or combined areas (e.g., “Africa,” “Asia”) that do not have ISO country codes.</li>
<li>For the analysis, we will focus on countries with valid ISO codes and exclude regions or combined areas without specific country codes.</li>
<li>Therefore, the following aggregated regions such as FAO regional groups, income categories, and political regions were removed as part of the data cleaning process. These entries represent regional or economic aggregates that do not correspond to specific, identifiable nations. Including them in the analysis would distort country-level comparisons and mask the true performance of individual nations in terms of macronutrient consumption.</li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load cleaned data after removing regions</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>cleaned_data <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(data_cleaned)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Display missing values after cleaning</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>post_clean <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(missing_post_clean)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>post_clean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        Country            Code            Year  Animal_Protein Vegetal_Protein 
              0               0               0               0               0 
            Fat   Carbohydrates 
              0               0 </code></pre>
</div>
</div>
</section>
<section id="duplicates-analysis" class="level4">
<h4 class="anchored" data-anchor-id="duplicates-analysis">Duplicates Analysis</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Duplicate check</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>duplicate_count <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(duplicate_check)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>duplicate_count</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<ul>
<li>The data cleaning process revealed no duplicate entries in the dataset. This ensures that each observation is unique and accurately represents a specific country and year combination.</li>
</ul>
</section>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<section id="global-trends-in-macronutrient-consumption" class="level4">
<h4 class="anchored" data-anchor-id="global-trends-in-macronutrient-consumption">Global Trends in Macronutrient Consumption</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the summarized data by year</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>summary_data <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(summary_data)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot global trends in macronutrient consumption</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>plot_1 <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(plot_trends)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>plot_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the absolute values of daily kilocalorie intake per person for each macronutrient (Animal Protein, Vegetal Protein, Fat, and Carbohydrates) from 1960 to 2020. Helps understand the growth in consumption volume over the years, highlighting the rise in fat intake and the relatively stable intake of proteins.</p>
<ul>
<li><p>Carbohydrates: Carbohydrates have consistently been the largest source of daily energy, providing over 1500 kcal per person per day. While relatively stable, there has been a slow but steady increase over time, suggesting that staples like rice, wheat, and maize continue to be dietary mainstays across the world.</p></li>
<li><p>Fat Consumption: Fat intake has shown a steady climb since 1961, with sharper increases noticeable after the 1980s. This growth likely reflects shifts towards more processed foods and calorie-dense diets as countries urbanize and food systems globalize. The steady rise in fat consumption suggests changing eating habits that prioritize richer, high-energy foods.</p></li>
<li><p>Protein Intake: Both animal-based and plant-based proteins have seen modest growth, remaining under 500 kcal per person per day. Animal protein consumption has increased gradually, especially in wealthier nations with rising meat consumption. Vegetal protein remains steady, reflecting its role in more plant-based diets, especially in Asia and Africa.</p></li>
</ul>
</section>
<section id="exploring-top-3-countries-for-animal-protein-consumption-by-decade" class="level4">
<h4 class="anchored" data-anchor-id="exploring-top-3-countries-for-animal-protein-consumption-by-decade">Exploring Top 3 Countries for Animal Protein Consumption by Decade</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute Top 3 for Animal Protein </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>top3_animal_protein <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(top3_animal_protein)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot top 3 countries for Animal Protein by decade</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>plot_top3_animal_protein <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(plot_top3_animal_protein)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>plot_top3_animal_protein</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>From the Analysis of Animal Protein Consumption by Decade the key observations are as follows:</p>
<ul>
<li><p>Iceland’s Consistent Top Position Iceland consistently ranks as the highest consumer of animal protein per person across all observed decades. The average daily intake in Iceland was 358.1 kcal in 1960 and steadily increased to 426.1 kcal by 2010, with a slight decrease to 421 kcal in 2020. This trend indicates strong dietary reliance on animal-based food sources that has remained stable over time.</p></li>
<li><p>Shifts in Leading Countries Over Time While Iceland’s position remained constant, the second and third spots varied: In the 1960s and 1970s, Australia and New Zealand were prominent, reflecting their strong livestock industries. During the 1980s and 1990s, France emerged as a leading consumer alongside Hong Kong, which continued to rank highly in subsequent decades. By 2020, Mongolia entered the top three for the first time, suggesting increased animal protein consumption in the region.</p></li>
<li><p>Changes in Consumption Levels The plot indicates an overall increase in animal protein consumption among the top-ranking countries over the six-decade span. Iceland’s average intake grew by approximately 68 kcal per person per day from 1960 to 2020, highlighting a steady upward trend. Notably, Hong Kong saw substantial growth, particularly evident from 2010 onwards, indicating rising consumption levels.</p></li>
</ul>
</section>
<section id="macronutrient-proportion-analysis" class="level4">
<h4 class="anchored" data-anchor-id="macronutrient-proportion-analysis">Macronutrient Proportion Analysis</h4>
<p>The stacked area chart illustrates the shifting proportions of global caloric intake from 1961 to 2022. It visualizes how different macronutrients—Animal Protein, Vegetal Protein, Fat, and Carbohydrates, contribute to the global dietary structure over time.</p>
<ul>
<li>The plot represents the proportion of global caloric intake for each macronutrient annually.</li>
<li>For each year, the total caloric intake for all countries combined is computed, and the contribution of each macronutrient is expressed as a fraction of this total.</li>
<li>This perspective reveals the relative share of each macronutrient in the global diet, highlighting dietary shifts over the decades.</li>
<li>The stacked area design effectively captures the long-term trends, such as the steady dominance of carbohydrates, the gradual increase in fat consumption, and the relative stability of protein sources.</li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Aggregating by macronutrient</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>sum_data <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(sum_data)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculating proportions</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>calorie_prop <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(calorie_prop)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Converting to wide format</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>long_prop <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(long_prop)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot proportions of macronutrients</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>plot_proportions <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(plot_proportions)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>plot_proportions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Carbohydrates Remain Dominant: Carbohydrates consistently account for the largest proportion of global caloric intake. Despite some fluctuations, their share has remained relatively stable over six decades, indicating a strong global reliance on carbohydrate-rich staples like grains and starchy vegetables.</p></li>
<li><p>Gradual Rise in Fat Consumption: The proportion of calories derived from fat has shown a noticeable increase, particularly since the 1980s. This growth reflects dietary shifts towards higher-fat food items, potentially driven by increased consumption of processed foods and oils. The rise is gradual but steady, signaling a global trend towards richer, calorie-dense diets.</p></li>
<li><p>Stable Share of Animal and Vegetal Protein: The relative contribution of Animal Protein and Vegetal Protein to the total caloric intake has remained largely unchanged. While absolute consumption has grown, their proportional share of the total global caloric intake has not shifted significantly. This indicates that while populations are consuming more food overall, the balance between protein sources remains steady.</p></li>
</ul>
<p>Conclusion: The stacked area chart effectively captures long-term global dietary patterns. Carbohydrates continue to be the primary source of global energy intake. Fat consumption, while still secondary, is the only macronutrient with a visibly increasing share. Meanwhile, Animal and Vegetal Protein maintain consistent proportions, reflecting stable dietary roles over the decades.</p>
</section>
</section>
<section id="modelling-fat-consumption" class="level2">
<h2 class="anchored" data-anchor-id="modelling-fat-consumption">Modelling Fat Consumption</h2>
<p>The time series for global fat consumption was created using the annual global average fat consumption data from 1961 to 2022. The summary statistics of the time series are as follows:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Preparing the data for time series modeling </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>fat_ts <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(fat_ts)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary time series data </span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>summary_fat_ts <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(summary_fat_ts)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>summary_fat_ts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  489.0   584.8   660.5   665.9   748.2   854.9 </code></pre>
</div>
</div>
<ul>
<li>Minimum Consumption: 489 kcal per person per day (observed in the early 1960s).</li>
<li>1st Quartile: 585 kcal per person per day.</li>
<li>Median: 661 kcal per person per day.</li>
<li>Mean: 666 kcal per person per day.</li>
<li>3rd Quartile: 748 kcal per person per day.</li>
<li>Maximum Consumption: 855 kcal per person per day (observed in recent years).</li>
</ul>
<p>These figures reflect a significant rise in global fat consumption per person over time, with notable accelerations in the 1990s and 2010s. The observed upward trend indicates a gradual increase in dietary fat intake worldwide.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Time series plot</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>plot_fat_ts <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(plot_fat_ts)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>plot_fat_ts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The time series plot illustrates a steady and relatively linear increase in average fat consumption over the 61-year period. This consistent upward trend suggests a global dietary shift towards higher fat intake, influenced by changes in dietary habits, economic development, and food availability.</li>
<li>The slope of the increase indicates a gradual but persistent rise, suggesting that the global trend in fat consumption has not been significantly disrupted by global events during the observed period.</li>
<li>The maximum recorded average consumption of 855 kcal per person per day in recent years marks a considerable increase from the early 1960s.</li>
</ul>
<section id="arima-model-fit" class="level4">
<h4 class="anchored" data-anchor-id="arima-model-fit">ARIMA Model Fit</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ARIMA model </span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>fat_arima <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(fat_arima)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Model Summary</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>fat_arima_summary <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(fat_arima_summary)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>fat_arima_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Series: fat_ts 
ARIMA(0,1,0) with drift 

Coefficients:
       drift
      5.9994
s.e.  0.6371

sigma^2 = 25.17:  log likelihood = -184.43
AIC=372.87   AICc=373.08   BIC=377.09

Training set error measures:
                      ME     RMSE      MAE          MPE      MAPE      MASE
Training set 0.007790046 4.935827 3.600444 -0.005469347 0.5343166 0.5723284
                  ACF1
Training set 0.1625095</code></pre>
</div>
</div>
<p>The ARIMA model selected by auto.arima() for global average fat consumption data is an ARIMA(0,1,0) with drift, indicating that the model captures the trend as a random walk with drift.</p>
<p><strong>Model Coefficient</strong></p>
<ul>
<li>Drift: The model estimates an average increase of approximately 6 kcal per year in global average fat consumption. This reflects a gradual and consistent rise in fat intake per person over the decades.</li>
<li>Standard Error of Drift: The standard deviation of the drift estimate is approximately 0.64, indicating relatively low variability around the average increase.</li>
</ul>
<p><strong>Model Diagnostics</strong></p>
<ul>
<li>Residual Variance: The variance of the residuals is around 25.17, indicating moderate variability in prediction errors. Log Likelihood: -184.43, suggesting that the model fits the data reasonably well.</li>
<li>AIC: 372.87, AICc: 373.08, BIC: 377.09, indicating a well-fitted model without excessive complexity.</li>
</ul>
<p><strong>Error Metrics</strong></p>
<ul>
<li>Mean Error (ME): 0.008 kcal, indicating almost negligible bias.</li>
<li>Root Mean Square Error (RMSE): 4.94 kcal, reflecting the average error magnitude.</li>
<li>Mean Absolute Error (MAE): 3.60 kcal, showing that the model’s average absolute deviation from observed values is minimal.</li>
<li>Mean Absolute Percentage Error (MAPE): 0.53%, indicating very high predictive accuracy.</li>
<li>Autocorrelation at Lag 1 (ACF1): 0.16, suggesting low autocorrelation in residuals.</li>
</ul>
</section>
<section id="forecast" class="level4">
<h4 class="anchored" data-anchor-id="forecast">Forecast</h4>
<section id="forecast-analysis" class="level5">
<h5 class="anchored" data-anchor-id="forecast-analysis">Forecast Analysis</h5>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ARIMA Forecasting</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>fat_forecast <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(fat_forecast)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the forecast</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>plot_fat_forecast <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(plot_fat_forecast)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>plot_fat_forecast</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>The ARIMA model forecasts that global average fat consumption will continue to increase at an approximate rate of 6 kcal per person per day over the next decade (2023–2032).</p>
<ul>
<li>The solid black line in the plot represents actual global average fat consumption from 1961 to 2022.</li>
<li>The blue line shows forecasted values for the next 10 years, indicating a consistent upward trend.</li>
<li>The light blue area marks the 80% confidence interval, and the dark blue area marks the 95% confidence interval. These intervals reflect the range within which future values are likely to fall.</li>
</ul>
</section>
</section>
<section id="predicted-vs-actual" class="level4">
<h4 class="anchored" data-anchor-id="predicted-vs-actual">Predicted vs Actual</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load global trends with predictions</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>global_trends_predicted <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(global_trends_predicted)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot Actual vs Predicted</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>plot_actual_vs_predicted <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(plot_actual_vs_predicted)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>plot_actual_vs_predicted</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The plot compares the actual global average fat consumption from 1961 to 2022 with the predicted values from the ARIMA(0,1,0) with drift model.</li>
<li>The red line shows observed fat consumption, while the dashed blue line represents predictions.</li>
<li>The model accurately captures the upward trend with minimal deviation, demonstrating strong predictive alignment.</li>
<li>Minor discrepancies are visible during rapid increases but do not impact overall reliability.</li>
<li>Error metrics, RMSE of 4.94, MAE of 3.60, and MAPE of 0.53%, indicate high predictive accuracy.</li>
</ul>
</section>
<section id="residual-diagnostics" class="level4">
<h4 class="anchored" data-anchor-id="residual-diagnostics">Residual Diagnostics</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Residuals</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>residual_diagnostics_test <span class="ot">&lt;-</span> <span class="fu">tar_read</span>(residual_diagnostics_test)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>residual_diagnostics_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(0,1,0) with drift
Q* = 9.3382, df = 10, p-value = 0.5003</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Residual plot</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="fu">tar_read</span>(residual_diagnostics_plot))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="residuals_diagnostics_plot.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>The ARIMA(0,1,0) with drift model was evaluated using residual diagnostics: - Ljung-Box Test: A p-value of 0.5003 indicates no significant autocorrelation, suggesting the model captured the time-dependent structure well. - Residual Plot: Residuals fluctuate around zero with occasional spikes but remain mostly stable. - ACF Plot: Minimal autocorrelation is observed, with most lags within confidence intervals. - Density Plot: Residuals are approximately normally distributed with slight skew.</p>
<p>Overall, the diagnostics confirm the model’s reliability for forecasting global fat consumption.</p>
</section>
</section>
<section id="model-output-and-eda-discussion" class="level2">
<h2 class="anchored" data-anchor-id="model-output-and-eda-discussion">Model Output and EDA Discussion</h2>
<ul>
<li><p>The ARIMA(0,1,0) with drift model effectively captures the upward trend in global fat consumption observed in the Global Trends in Macronutrient Consumption (1961 - 2022) plot. The model’s estimated drift of 5.99 kcal per person per year aligns with the steady increase shown in the EDA visualization, demonstrating its reliability in modeling long-term growth.</p></li>
<li><p>The Proportion of Global Caloric Intake by Macronutrient plot highlights fat’s rising share over time, which the ARIMA model projects into future periods. While carbohydrates remain dominant and protein sources stable, fat’s contribution has grown steadily. The Actual vs.&nbsp;Predicted plot shows strong alignment, with low error metrics (RMSE: 4.94, MAE: 3.60, MAPE: 0.53%), affirming predictive accuracy.</p></li>
<li><p>Residual diagnostics confirm well-behaved residuals with no significant autocorrelation, validating the model’s capacity to capture fat consumption trends effectively.</p></li>
</ul>
<p>Overall, the ARIMA model not only matches historical EDA trends but also projects them confidently into the future, demonstrating accuracy and consistency in reflecting global dietary shifts.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The analysis of global macronutrient consumption from 1961 to 2022 reveals clear trends: carbohydrates remain the largest source of calories, while fat consumption has steadily increased. The ARIMA(0,1,0) model effectively captured this upward trend, forecasting continued growth in fat intake over the next decade. Iceland consistently emerged as the top consumer of animal protein across decades, reflecting stable dietary patterns. Overall, the data indicates persistent global dietary habits, with rising fat consumption pointing to broader nutritional shifts and changing food preferences worldwide.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>