{
  "hash": "20caef80e9fb6a716aeb224526401741",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Diving Deeper into Data Exploration: Introduction\"\nauthor: \"Pooja Rajendran Raju\"\ndate: \"Aug 5, 2024\"\nquarto-required: \">=1.3.0\"\noutput: \n  html_document:\n    css: assignment.css\ncategories: [Exploration]\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n## Introduction\n\nThe data to used is available from [Tidy Tuesday 28 May 2024 page](https://github.com/rfordatascience/tidytuesday/blob/master/data/2024/2024-05-28/readme.md). Downloaded the data from here, using the `tidytuesdayR` package. \n\nIn addition the `gardenR` package, available from `remotes::install_github(\"llendway/gardenR\")` has extra details about the garden. \n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n## Exploration \n\na. How many types of vegetables were grown in each year?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Reading the data\nplanting_2020 <- read.csv(\"data/planting_2020\")\nplanting_2021 <- read.csv(\"data/planting_2021\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Counting number of unique vegetables in 2020\nvegetables_2020 <- planting_2020 |> \n                   select(vegetable) |>\n                   unique() |> \n                   count() |>\n                   rename(count_2020 = n )\n\n# Counting number of unique vegetables in 2021\nvegetables_2021 <- planting_2021 |> \n                   select(vegetable) |>\n                   unique() |>\n                   count() |> \n                   rename(count_2021 = n )\n\ncbind(vegetables_2020, vegetables_2021)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  count_2020 count_2021\n1         31         26\n```\n\n\n:::\n:::\n\n\n- In 2020, 31 types of vegetables were grown, where as in 2021 only 26 types of vegetables were grown. \n\nb. How many vegetables were grown in 2020 that were not grown in 2021? \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Creating variable with all unique vegetables in 2020\nunique_2020 <- planting_2020 |> \n                   select(vegetable) |>\n                   unique()\n\n# Creating variable with all unique vegetables in 2021\nunique_2021 <- planting_2021 |> \n                   select(vegetable) |>\n                   unique()\n\n# Using anti_join to get the vegetables grown in 2020 but not in 2021 \ndifference_2020 <- anti_join(unique_2020, unique_2021, by = c(\"vegetable\"))\n\n# Counting the number of vegetables grown in 2020 but not in 2021 \nnrow(difference_2020)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n\n```{.r .cell-code}\ndifference_2020\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vegetable\n1       Swiss chard\n2          broccoli\n3          pumpkins\n4       hot peppers\n5  brussels sprouts\n6          jalapeño\n7             melon\n8          rudabaga\n9      strawberries\n10         kohlrabi\n```\n\n\n:::\n:::\n\n\n- 10 vegetables were grown in 2020 that were not grown in 2021. The vegetables are listed in the table above. \n\n\nc. What are some of the data recording errors that can be seen by comparing vegetables grown in each year?\n\n- The names of vegetables and varieties are not recorded in a consistent manner. In some places, the first letter is capitalized and in other places its not. Variations in the use of upper and lower case when spelling the same vegetable/variety. \n- For different years, the same vegetable is spelled differently. Mistakes in spelling the vegetable.\n- In some places the vegetables/variety is written in singular and other places its in plural \n- Examples in planting data for 2020 and 2021:\na. In planting_2021 - __swiss chard__ ; In planting _2020 - __Swiss Chard__ \n- Here, S in \"swiss\" is in uppercase for 2020, whereas in 2021 it is lower case. \n\nb. In planting_2021 - __pumpkin__ ; In planting _2020 - __pumpkins__\n- Here, \"pumpkin\" is written as singular in 2021, whereas in 2020 it is written in plural. \n\nc. In planting_2021 - __rutabaga__ ; In planting _2020 - __rudabaga__\n- Here, \"rutabaga\" is misspelled while recording data in 2020 as \"rudabaga\" instead as rutabaga. \n\n- Similar inconsistencies can be found in the variable \"variety\".\n- These data recording errors can lead to incorrect analysis as functions like \"unique\" are case sensitive.  \n\n\n\n\n## Exploring harvest data from two years\n\na. Joining the harvest data for the two years, after adding a new variable each, called `year`. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Reading the data\nharvest_2020 <- read.csv(\"data/harvest_2020\")\nharvest_2021 <- read.csv(\"data/harvest_2021\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Adding variable year to harvest_2020\nharvest_2020 <- harvest_2020 |> \n                mutate( year = year(date))\n\n# Adding variable year to harvest_2021\nharvest_2021 <- harvest_2021 |> \n                mutate( year = year(date))\n\n# Joining Data \ncombined_harvest <- full_join(harvest_2020, harvest_2021)\n```\n:::\n\n\nb. For the `tomatoes` compareing the weight of the harvest in both years.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculating the weight of harvest for tomatoes in 2020\nweight_2020 <- harvest_2020 |> \n               filter(vegetable == \"tomatoes\") |> \n               select(weight) |>\n               sum()\n\n# Calculating the weight of harvest for tomatoes in 2021\nweight_2021 <- harvest_2021 |> \n               filter(vegetable == \"tomatoes\") |> \n               select(weight) |>\n               sum()\n\ncbind(weight_2020, weight_2021)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     weight_2020 weight_2021\n[1,]      158231      141509\n```\n\n\n:::\n:::\n\n\n- The weight of harvest for tomatoes in 2020 is 158231 grams and the weight of harvest for tomatoes in 2021 is 141509 grams. The weight of harvest is more in 2020 as compared to that in 2021. \n\nc. Explaining what might be a problem when comparing the tomato yield from these two years.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninconsistency <- combined_harvest |>\n     select(vegetable, variety, year) |>\n     filter(vegetable == \"tomatoes\") |>\n     group_by(variety, year) |>\n     count() |> \n     pivot_wider(names_from = year, values_from = n)\n\nhead(inconsistency, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n# Groups:   variety [6]\n  variety     `2020` `2021`\n  <chr>        <int>  <int>\n1 Amish Paste     30     19\n2 Better Boy      23     NA\n3 Big Beef        21     24\n4 Black Krim      12     12\n5 Bonny Best      27     15\n6 Brandywine      16     NA\n```\n\n\n:::\n:::\n\n\n- Based on the output of the code above, we can observe that in both years the same varieties of tomatoes were not harvested. There is no consistency with the varieties harvested in both years. \n- Further, for same varieties harvested in both years, the number of harvests are different. \n\n## Exploring planting data with garden layout\n\nThe planting data has the label of the garden plot where each vegetable is grown. The `gardenR` package has the spatial coordinates of these spots in the garden. \n\n- Join the `planting_2020` and `planting_2021` data, after adding a variable labeling the year. And then joining with the `garden_coords` data, so that the locations of each plot are recorded.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Reading garden_coords data\ngarden_coords <- read.csv(\"data/garden_coords\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Adding variable year to harvest_2020\nplanting_2020 <- planting_2020 |> \n                mutate( year = year(date))\n\n# Adding variable year to harvest_2021\nplanting_2021 <- planting_2021 |> \n                mutate( year = year(date))\n\n# Joining planting data of 2020 and 2021\ncombined_20_21 <- full_join(planting_2020, planting_2021)\n\n# Joining combined planting data of 2020 and 2021 with garden coordinates\nplanting_coords <- full_join(combined_20_21 , garden_coords, by = \"plot\")\n```\n:::\n\n\n- Plot garden layout, with locations of tomatoes coloured, facetted by year.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Creating data for labels\nfor_labs <- garden_coords |>\n  group_by(plot) |>\n  summarize(x = mean(x), y = mean(y), .groups = 'drop')\n\n# Plotting the garden layout\nggplot() +\n  geom_polygon(data = planting_coords |> filter(!is.na(year)),                \n               aes(x = x, y = y, group = plot), \n               color = \"black\") +\n  geom_polygon(data = planting_coords |> filter(vegetable == \"tomatoes\"),\n               aes(x = x, y = y, group = plot), \n               fill = \"red\", \n               alpha = 0.5, \n               color = \"black\") + \n  geom_text(data = for_labs, \n            aes(x = x, y = y, label = plot), \n            color = \"yellow\",\n            size = 5) +\n  theme_void() +\n  theme(panel.background = element_rect(fill = \"darkgray\")) + \n  facet_wrap(~year)\n```\n\n::: {.cell-output-display}\n![Garden Plot Layout](index_files/figure-html/gardenplot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- The above plot shows the garden plot with the locations of tomatoes highlighted in red for years 2020 and 2021. \n- In 2020, plots N and J are fully planted with tomatoes, while plot O has been planted with tomatoes along with few other vegetables. \n- In 2021, plots N and D are fully planted with tomatoes, while plot O has been planted with tomatoes along with few other vegetables.\n\n\n## Generative AI analysis\n\n- I used generative AI to understand what kind of data inconsistencies to look for in the datasets. \n- I used it to find information on functions like unique, full_join and bind_rows. \n- Further, I used it to understand how to layer the geom_polygon function to make the garden plot, coloring the locations of tomatoes differently. I faced issues while trying to color the plot of tomatoes differently and I wasn't sure how to add two layers of geom_polygon to the same plot and if it is possible at all. With the use of ChatGPT, I was able to arrive at the solution using the questions in the link to my ChatGPT chat history. \n- I also used it to understand if the function \"filter\" can be used when passing data to geom_polygon and I was able to clarify my doubt with the help of ChatGPT. \n\n## Citations \n\n1. Lendway, L (2024). gardenR: Gardening Resources and Tools. R package <https://github.com/llendway/gardenR>\n\n2. Wickham, H, Chang, W, Wickham, M, Hester, J, Bryan, J, & others (2024). tidyverse: R package version 2.0.0, <https://CRAN.R-project.org/package=tidyverse>\n\n3. OpenAI, 2024. ChatGPT (Version 4) <https://www.openai.com/chatgpt>\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}