<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="CUSCUS - Pooja Rajendran Raju &amp; Thi My Ngoc Tran">
<meta name="dcterms.date" content="2024-09-24">

<title>Do different sensors at the same location report the same values?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="report_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="report_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


<link rel="stylesheet" href="assignment.css">
</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Do different sensors at the same location report the same values?</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>CUSCUS - Pooja Rajendran Raju &amp; Thi My Ngoc Tran </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 24, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<!-- 
Write an introductory paragraph explaining what the measurements of `pm25`, `pm10`, `so2`, `o3`, `no2`, `co` are and how they relate to problematic air.
-->
<p>Pollutants with the strongest evidence for public health concern include particulate matter (PM), sulfur dioxide (SO2), ozone (O3), nitrogen dioxide (NO2) and carbon monoxide (CO)</p>
<ul>
<li><p><em>Particulate Matter</em> (<code>pm25</code>, <code>pm10</code>): consists of tiny particles in the air that can be inhaled. <code>pm25</code> refers to particles smaller than 2.5 micrometers, while <code>pm10</code> includes larger particles up to 10 micrometers. These particles originate from various sources, such as traffic emissions, industrial activities, construction sites, and natural sources like pollen and dust. Because they are small enough to penetrate deep into the lungs and even enter the bloodstream, high concentrations of <code>pm25</code>, <code>pm10</code> are associated with poor air quality and can lead to serious health issues, including respiratory and cardiovascular problems.</p></li>
<li><p><em>Sulfur dioxide</em> (<code>so2</code>) is a colorless gas that is readily soluble in water. It mainly comes from the combustion of fossil fuels for domestic heating, industries and power generation. Exposure to SO2 is associated with asthma hospital admissions and emergency room visits.</p></li>
<li><p><em>Ozone</em> (<code>o3</code>) is a key ingredient in smog, created when sunlight reacts with pollutants like volatile organic compounds, carbon monoxide, and nitrogen oxides from vehicles and industries. Because it forms in sunlight, ozone levels are often highest on sunny days. Additionally, some household devices, like portable air cleaners, can also produce ozone. Exposure to excessive ozone can cause problems breathing, trigger asthma, reduce lung function and lead to lung disease.</p></li>
<li><p><em>Nitrogen dioxide</em> (<code>no2</code>) is a reddish-brown gas that is soluble in water, and a strong oxidant. It mainly comes from burning fuels in heating, transportation, industry, and power generation, as well as from household appliances like furnaces and gas stoves. Exposure to NO₂ can irritate the airways and worsen respiratory diseases. It also contributes to ozone formation, linking it to asthma and other respiratory issues.</p></li>
<li><p><em>Carbon monoxide</em> (<code>co</code>) is a colorless, odorless gas produced from the incomplete burning of fuels like wood, petrol, coal, and natural gas. The main source of CO in the air is motor vehicles. Carbon monoxide diffuses across the lung tissues and into the bloodstream, making it difficult for the body’s cells to bind to oxygen. This lack of oxygen damages tissues and cells. Exposure to carbon monoxide can cause difficulties breathing, exhaustion, dizziness, and other flu-like symptoms. Exposure to high levels of carbon monoxide can be deadly.</p></li>
</ul>
<p><strong>Do different sensors at the same location report the same values?</strong></p>
<p>The question being assessed focuses on analyzing if sensors placed within close proximity report same values. Analyzing data from these varied suburban and urban sensors helps to determine if air quality measurements are consistent across these distinct environments or if local geographic and environmental factors lead to significant differences in reported values. Such insights will clarify how air quality varies across coastal and urban settings, helping to assess whether sensor readings can be directly compared or if adjustments are needed for accurate regional air quality assessments. This can improve the relevance of public health responses and policies specific to each area’s unique conditions.</p>
<p><strong>Expectations</strong>:</p>
<ul>
<li><p>Sensor data from locations like Melbourne are expected to show higher pollution levels compared to areas like Geelong South, which is closer to the coast.</p></li>
<li><p>A positive correlation is anticipated between pollutant levels, where an increase in one pollutant is likely to correspond with increases in others.</p></li>
<li><p>Weekday and weekend trends in pollutant levels are expected to differ, potentially reflecting variations in daily activities and emissions.</p></li>
</ul>
<p><strong>Limitations</strong>:</p>
<ul>
<li><p>Not all locations have sensors that measure every pollutant. Most sensors capture data for only two pollutants, with exceptions like Alphington and Geelong South, which measure a broader range.</p></li>
<li><p>There may be significant missing data for certain pollutants, which could affect analysis outcomes.</p></li>
<li><p>The varying scales and units of pollutants may complicate direct comparisons.</p></li>
<li><p>As the data originates from third-party organizations and government agencies, there could be occasional concerns about data accuracy and consistency.</p></li>
</ul>
</section>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">Data description</h2>
<p><strong>Data Source</strong></p>
<p>OpenAQ is an open-source platform that aggregates real-time air quality data from governmental and research sources worldwide. Using sensors managed by environmental agencies, OpenAQ collects pollutant measurements such as PM2.5, ozone, and nitrogen dioxide. The data is standardized and made accessible on their platform, enabling researchers, policymakers, and the public to monitor air quality, track trends, and support efforts to enhance environmental health globally.</p>
<p><strong>License</strong></p>
<p>OpenAQ provides air quality data aggregated from multiple sources, each with its own licensing terms. While some data might be available under open licenses such as Creative Commons (e.g., CC0), others may require attribution, restrict commercial use, or have specific conditions as determined by the original providers. OpenAQ includes these license details to ensure users comply with any necessary terms when accessing or using the data.</p>
<p><strong>Data</strong></p>
<p>This dataset captures air quality measurements across various locations in Australia, focusing on pollutant levels such as particulate matter (e.g., PM10, PM2.5) over time. It provides spatial and temporal data, including the concentration of pollutants, the geographic location of sampling sites, and time-stamps for when each measurement was recorded. The data allows for a detailed analysis of air quality trends, helping to assess pollution levels and their potential impacts on public health. By studying these pollutant concentrations over time and location, it becomes possible to identify pollution hot spots, track seasonal variations, and evaluate overall compliance with air quality standards.</p>
<p>The dataset contains 36,326 rows and 9 columns. The variables in the dataset are as follows:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data_description <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">c</span>(<span class="st">"location_id"</span>, <span class="st">"location"</span>, <span class="st">"parameter"</span>, <span class="st">"value"</span>, <span class="st">"date_utc"</span>, <span class="st">"unit"</span>, <span class="st">"lat"</span>, <span class="st">"long"</span>, <span class="st">"country"</span>),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Description =</span> <span class="fu">c</span>(</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Unique identifier for each location."</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Name of the location where measurements were taken."</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Type of pollutant measured: PM10, PM25, SO2, NO2, CO, O3"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Recorded value of the pollutant."</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Timestamp in UTC for the recorded measurement"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Measurement unit, primarily µg/m³ and ppm"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Latitude co-ordinates for the location"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Longitude co-ordinates for the location"</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Country code (AU for all records)"</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(data_description, <span class="at">caption =</span> <span class="st">"Description of Data Variables"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Description of Data Variables</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">location_id</td>
<td style="text-align: left;">Unique identifier for each location.</td>
</tr>
<tr class="even">
<td style="text-align: left;">location</td>
<td style="text-align: left;">Name of the location where measurements were taken.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">parameter</td>
<td style="text-align: left;">Type of pollutant measured: PM10, PM25, SO2, NO2, CO, O3</td>
</tr>
<tr class="even">
<td style="text-align: left;">value</td>
<td style="text-align: left;">Recorded value of the pollutant.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">date_utc</td>
<td style="text-align: left;">Timestamp in UTC for the recorded measurement</td>
</tr>
<tr class="even">
<td style="text-align: left;">unit</td>
<td style="text-align: left;">Measurement unit, primarily µg/m³ and ppm</td>
</tr>
<tr class="odd">
<td style="text-align: left;">lat</td>
<td style="text-align: left;">Latitude co-ordinates for the location</td>
</tr>
<tr class="even">
<td style="text-align: left;">long</td>
<td style="text-align: left;">Longitude co-ordinates for the location</td>
</tr>
<tr class="odd">
<td style="text-align: left;">country</td>
<td style="text-align: left;">Country code (AU for all records)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Data Checking and Cleaning Methods</strong></p>
<ul>
<li><strong>Data Type Validation</strong>: - It is necessary to ensure that each column has the correct data type. For example, date_utc should be in datetime format for time series analysis.</li>
<li><strong>Handling Missing or Null values</strong>: Although no null values are detected, there may still be missing or erroneous data entries. It’s essential to review columns like value for potential issues like zero or extreme values that may indicate faulty measurements. Further, we might be able to discover missing values once the data is transformed into tidy form.</li>
<li><strong>Duplicate Records</strong>: Given that location_id and date_utc might uniquely identify each record, checking duplicates based on these columns to prevent redundant data.</li>
<li><strong>Outlier Detection</strong>: The value column could contain outliers. Outliers could be identified using statistical methods like IQR analysis. This is particularly important in environmental data to avoid skewed analyses.</li>
<li><strong>Unit Consistency</strong>: Ensure all entries use consistent units for accurate analysis.</li>
<li><strong>Location Summary</strong>: Check the number of observations at each location to determine if it is consistent for the selected time period.</li>
<li><strong>Parameter Distribution</strong>: Check for consistency in number of parameters measured at each location.</li>
</ul>
<!--
Download the data you need to answer your questions. Try downloading a small amount of data first. (Make sure you save a copy on your repo - assuming files size is not too large - and *turn off the code chunk that does the download*.) To download all the data you need might require downloading in chunks, like a week or two at a time. Your data needs to contain all 6 pollutants. The data that you work with needs to have **at least**:

    - two locations
    - two months
    - all six pollutants, with a sufficient number of not missings to be able to do some multivariate analysis of at least four. (See the next step to help manage missing values.)
-->
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># download data and save as csv file</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("devtools")</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#devtools::install_github("numbats/airpurifyr")</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#set_openaq_api_key("")</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">#melbourne &lt;- get_measurements_for_location(country = "AU", </span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#                                           city = "Melbourne",</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">#                                           date_from =as.Date("2024-07-01"), </span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">#                                           date_to = as.Date("2024-09-01"))</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">#geelong &lt;- get_measurements_for_location(country = "AU", </span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co">#                                       city = "Geelong",</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co">#                                       date_from = as.Date("2024-07-01"), </span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co">#                                       date_to = as.Date("2024-09-01"))</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co">#write.csv(melbourne, file = "melbourne.csv", row.names = FALSE)</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co">#write.csv(geelong, file = "geelong.csv", row.names = FALSE)</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co">#combine data</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co">#options(scipen = 999)</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="co">#original_df &lt;- bind_rows(melbourne, geelong)</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="co">#write.csv(original_df, file = "data/original_df.csv", row.names = FALSE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="initial-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="initial-data-analysis">Initial data analysis</h2>
<!--
4. You will need to aggregate the data at some level, because the measurements are like time stamps, that pollutants are not recorded at the same instant. Aggregating to hourly seems to provide reasonably complete data.

5. Pre-process the data as needed, and do necessary quality control checks of the data. We don't recommend imputing missings, at least do it sparingly, but exploring the missingness is very important.

-->
<section id="load-data" class="level4">
<h4 class="anchored" data-anchor-id="load-data">Load data</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Load data</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>original_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/original_df.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Population</strong></p>
<ul>
<li>The population of interest in this context would be all sensors deployed at the same location that measure the same type of pollutants over a given period of time.</li>
</ul>
</section>
<section id="data-screening" class="level4">
<h4 class="anchored" data-anchor-id="data-screening">Data Screening</h4>
<p><strong>Evaluating Data Type Composition</strong></p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vis_dat</span>(original_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Understanding the composition of variable types in the dataset using <em>‘vis_dat’</em>. Here, the dataset primarily comprises of character type variables, numeric variables, POSIXct and POSIXt variables used to efficiently represent date-time objects.</li>
<li>Based on observing the dataset, it appears that not all sensors measure all pollutants, hence once in tidy format we will be able to explore the missing values.</li>
</ul>
<p><strong>Checking for Duplicate Rows</strong></p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Detecting duplicate rows</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">duplicated</span>(original_df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p><strong>Checking Unit Consistency</strong></p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(original_df<span class="sc">$</span>unit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "µg/m³" "ppm"  </code></pre>
</div>
</div>
<p><strong>Evaluating the structure of Data</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(original_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 36,326
Columns: 9
$ location_id &lt;dbl&gt; 10494, 10494, 10494, 10494, 10494, 104…
$ location    &lt;chr&gt; "Alphington", "Alphington", "Alphingto…
$ parameter   &lt;chr&gt; "pm25", "pm25", "pm25", "pm25", "pm25"…
$ value       &lt;dbl&gt; 2.68, 5.50, 3.76, 1.61, 1.88, 3.80, 5.…
$ date_utc    &lt;dttm&gt; 2024-09-01 00:00:00, 2024-08-31 23:00…
$ unit        &lt;chr&gt; "µg/m³", "µg/m³", "µg/m³", "µg/m³", "µ…
$ lat         &lt;dbl&gt; -38, -38, -38, -38, -38, -38, -38, -38…
$ long        &lt;dbl&gt; 145, 145, 145, 145, 145, 145, 145, 145…
$ country     &lt;chr&gt; "AU", "AU", "AU", "AU", "AU", "AU", "A…</code></pre>
</div>
</div>
<ul>
<li>The glimpse function provides an overview of a dataset by displaying each variable’s name, its data type, and a sample of the initial values. This allows for a quick examination of the dataset’s structure, making it easier to confirm data types and gain an immediate understanding of the data.</li>
</ul>
<p><strong>Creating a location Summary</strong></p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>location_summary <span class="ot">&lt;-</span> original_df <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(location) <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>())</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(location_summary, </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Location Summary"</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<table class="table table-striped table-hover table-sm small" data-quarto-postprocess="true">
<caption>Location Summary</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">location</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alphington</td>
<td style="text-align: right;">8507</td>
</tr>
<tr class="even">
<td style="text-align: left;">Box Hill</td>
<td style="text-align: right;">1445</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brighton</td>
<td style="text-align: right;">1391</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brooklyn</td>
<td style="text-align: right;">2817</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dandenong</td>
<td style="text-align: right;">5697</td>
</tr>
<tr class="even">
<td style="text-align: left;">Footscray</td>
<td style="text-align: right;">2492</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Geelong South</td>
<td style="text-align: right;">7829</td>
</tr>
<tr class="even">
<td style="text-align: left;">Macleod</td>
<td style="text-align: right;">1437</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Melbourne CBD</td>
<td style="text-align: right;">1474</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mooroolbark</td>
<td style="text-align: right;">3237</td>
</tr>
</tbody>
</table>


</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of parameters in each location</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>parameter_count <span class="ot">&lt;-</span> original_df <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(location) <span class="sc">|&gt;</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">no_parameters =</span> <span class="fu">n_distinct</span>(parameter))</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(parameter_count, </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Number of Parameters in each Location"</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<table class="table table-striped table-hover table-sm small" data-quarto-postprocess="true">
<caption>Number of Parameters in each Location</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">location</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">no_parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alphington</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Box Hill</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brighton</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brooklyn</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dandenong</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Footscray</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Geelong South</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Macleod</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Melbourne CBD</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mooroolbark</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<ul>
<li>Based on the location summary, we observe inconsistencies in sensor readings across the dataset’s time period. Alphington and Geelong South each have approximately 8,000 observations, while Dandenong records around 6,000, with other locations having significantly fewer observations. This suggests that not all sensors capture data for every pollutant. Further, on exploring the number of parameters detected at each sensor location we can confirm that only Alphington and Geelong South detect all six pollutants. Hence, filtering the data to include locations with sufficient observations for all 6 pollutants.</li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Filter data of "Alphington" and "Geelong South" in July and August:</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>alp_gee <span class="ot">&lt;-</span> original_df <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(location <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Alphington"</span>, <span class="st">"Geelong South"</span>), </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>         date_utc <span class="sc">!=</span> <span class="fu">as.POSIXct</span>(<span class="st">"2024-09-01 00:00:00"</span>, <span class="at">tz =</span> <span class="st">"UTC"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(date_utc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Converting data to wider form to explore missingness </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>data_wider <span class="ot">&lt;-</span> alp_gee <span class="sc">|&gt;</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">select</span>(<span class="sc">-</span>unit)  <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>           <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> parameter,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">values_from =</span> value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="missing-data-evaluation" class="level4">
<h4 class="anchored" data-anchor-id="missing-data-evaluation">Missing Data Evaluation</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating the missing percentage for each location</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>missing_summary <span class="ot">&lt;-</span> data_wider <span class="sc">|&gt;</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)) <span class="sc">/</span> <span class="fu">n</span>() <span class="sc">*</span><span class="dv">100</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>( <span class="sc">-</span>location, <span class="sc">-</span>location_id, <span class="sc">-</span>date_utc, <span class="sc">-</span>lat, <span class="sc">-</span>long, <span class="sc">-</span>country) <span class="sc">|&gt;</span> </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"variable"</span>, </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"missing_percentage"</span>) </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Plotting the missing percentage for each variable</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(missing_summary, </span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(variable,<span class="sc">-</span>missing_percentage), </span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> missing_percentage))  <span class="sc">+</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend =</span> variable, <span class="at">yend =</span> <span class="dv">0</span>), <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Missing Data Percentage"</span>,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Pollutant"</span>,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Missing Percentage (%)"</span>) <span class="sc">+</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Based on the above plot, we can infer that the data is relatively complete with minimal missing values except for <code>no2</code>, which shows around 26% missing values. Further, exploring the missing data by location.</li>
</ul>
<p><strong>Exploring Missing Data by Location</strong></p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating the missing percentage for each location</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>missing_summary <span class="ot">&lt;-</span> data_wider <span class="sc">|&gt;</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(location <span class="sc">==</span> <span class="st">"Alphington"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)) <span class="sc">/</span> <span class="fu">n</span>() <span class="sc">*</span><span class="dv">100</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>( <span class="sc">-</span>location, <span class="sc">-</span>location_id, <span class="sc">-</span>date_utc, <span class="sc">-</span>lat, <span class="sc">-</span>long, <span class="sc">-</span>country) <span class="sc">|&gt;</span> </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"variable"</span>, </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"missing_percentage"</span>) </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Plotting the missing percentage for each variable</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(missing_summary, </span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(variable,<span class="sc">-</span>missing_percentage), </span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> missing_percentage))  <span class="sc">+</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend =</span> variable, <span class="at">yend =</span> <span class="dv">0</span>), <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Missing Data Percentage - Alphington"</span>,</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Pollutant"</span>,</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Missing Percentage (%)"</span>) <span class="sc">+</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating the missing percentage for each location</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>missing_summary <span class="ot">&lt;-</span> data_wider <span class="sc">|&gt;</span> </span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(location <span class="sc">==</span> <span class="st">"Geelong South"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)) <span class="sc">/</span> <span class="fu">n</span>() <span class="sc">*</span><span class="dv">100</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>( <span class="sc">-</span>location, <span class="sc">-</span>location_id, <span class="sc">-</span>date_utc, <span class="sc">-</span>lat, <span class="sc">-</span>long, <span class="sc">-</span>country) <span class="sc">|&gt;</span> </span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"variable"</span>, </span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"missing_percentage"</span>) </span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a><span class="co">#Plotting the missing percentage for each variable</span></span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(missing_summary, </span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(variable,<span class="sc">-</span>missing_percentage), </span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> missing_percentage))  <span class="sc">+</span></span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend =</span> variable, <span class="at">yend =</span> <span class="dv">0</span>), <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Missing Data Percentage - Geelong South"</span>,</span>
<span id="cb16-39"><a href="#cb16-39" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Pollutant"</span>,</span>
<span id="cb16-40"><a href="#cb16-40" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Missing Percentage (%)"</span>) <span class="sc">+</span></span>
<span id="cb16-41"><a href="#cb16-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb16-42"><a href="#cb16-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-43"><a href="#cb16-43" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">/</span> p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The data from Alphington is nearly complete, with less than 5% of values missing. In contrast, Geelong South has relatively complete data for most pollutants, with missing values ranging between 0% and 5%. However, for <code>pm10</code>, approximately 10% of data is missing, and for <code>no2</code>, there is a significant gap with around 45% of data missing.</li>
</ul>
<p><strong>Specific Date Analysis of Missing Data</strong></p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>alp_gee_ts <span class="ot">&lt;-</span> data_wider <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tsibble</span>(<span class="at">key =</span> location, <span class="at">index =</span> date_utc)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>alp <span class="ot">&lt;-</span> alp_gee_ts<span class="sc">|&gt;</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(location <span class="sc">==</span> <span class="st">"Alphington"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">count_gaps</span>(alp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  location   .from               .to                    .n
  &lt;chr&gt;      &lt;dttm&gt;              &lt;dttm&gt;              &lt;int&gt;
1 Alphington 2024-07-03 13:00:00 2024-07-03 13:00:00     1
2 Alphington 2024-07-15 05:00:00 2024-07-15 05:00:00     1
3 Alphington 2024-07-18 22:00:00 2024-07-19 07:00:00    10
4 Alphington 2024-08-15 10:00:00 2024-08-15 10:00:00     1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>gee <span class="ot">&lt;-</span> alp_gee_ts <span class="sc">|&gt;</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(location <span class="sc">==</span> <span class="st">"Geelong South"</span>) </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">count_gaps</span>(gee)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  location     .from               .to                    .n
  &lt;chr&gt;        &lt;dttm&gt;              &lt;dttm&gt;              &lt;int&gt;
1 Geelong Sou… 2024-07-03 13:00:00 2024-07-03 13:00:00     1
2 Geelong Sou… 2024-07-18 22:00:00 2024-07-19 07:00:00    10
3 Geelong Sou… 2024-08-15 10:00:00 2024-08-15 10:00:00     1
4 Geelong Sou… 2024-08-22 01:00:00 2024-08-22 03:00:00     3</code></pre>
</div>
</div>
<p>Between July and August 2024, both Alphington and Geelong South experienced several instances of missing data, with some overlaps. Both locations had a one-hour gap on July 3rd at 13:00 and a 10-hour gap from July 18th at 22:00 to July 19th at 07:00. Additionally, Alphington had gaps on July 15th at 05:00 and August 15th at 10:00, while Geelong South also missed data on August 15th at 10:00. Geelong South experienced a unique three-hour gap on August 22nd from 01:00 to 03:00.</p>
<p><strong>Analysis of Possible Factors Contributing to Missing Data</strong></p>
<p>Based on information from the OpenAQ documentation and GitHub resources, potential causes of data gaps across different sensor locations may include:</p>
<ol type="1">
<li><p>Monitoring stations typically measure specific pollutants based on local priorities, regulations, and resources, leading to incomplete data coverage for certain pollutants across regions.</p></li>
<li><p>OpenAQ uses both reference monitors and low-cost sensors. While low-cost sensors expand coverage, they may inconsistently measure pollutants like PM10 due to calibration and environmental factors, resulting in data gaps.</p></li>
<li><p>OpenAQ collects data from various government and third-party sources, each with different reporting practices. Changes in data-sharing agreements, or provider disruptions can cause temporary data gaps for certain pollutants.</p></li>
<li><p>Technical disruptions, such as routine sensor maintenance, calibration, network outages, power failures, and equipment malfunctions, can temporarily pause data transmission, leading to missing data.</p></li>
</ol>
<p>While the above offer a general overview of data handling and reasons for data gaps on the OpenAQ platform. For specific details on missing data, consulting the relevant data provider or monitoring station is often necessary, as they may have insights into the cause.</p>
</section>
<section id="detecting-outliers" class="level4">
<h4 class="anchored" data-anchor-id="detecting-outliers">Detecting Outliers</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(alp_gee <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">==</span> <span class="fu">c</span>(<span class="st">"pm10"</span>, <span class="st">"pm25"</span>)) , <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span>      <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>parameter ) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>From the boxplots we can deduce the following:</p>
<ul>
<li><code>pm10</code> has a wider spread and greater variability compared to <code>pm25</code>. Both pollutants have a narrow IQR, indicating low variability within the central 50% of values, with most data concentrated near the median. However, both also have numerous outliers, which are more extreme in <code>pm10</code> The spike in <code>pm10</code> levels may result from events like dust storms, construction, or excessive road dust, while the elevated <code>pm25</code> levels likely stem from combustion sources such as vehicle exhaust during peak traffic hours.</li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(alp_gee <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span>(parameter <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"pm10"</span>, <span class="st">"pm25"</span>))), <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>parameter, <span class="at">scales =</span> <span class="st">"free_x"</span> ) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>The <code>co</code> boxplot shows a narrow IQR, indicating low variability within the central 50% of data. The short whiskers and numerous outliers (up to about 1.5 ppm) suggest a concentrated distribution around the median but substantial variability in extreme values, suggesting occasional spikes in <code>co</code> concentration.</p></li>
<li><p>The <code>no2</code> boxplot reveals a narrow IQR, signifying low variability within the central 50% of data. The whiskers extend just beyond the box, with outliers reaching up to 0.06 ppm, indicating occasional peaks in <code>no2</code> concentrations and moderate variability in extreme values, though not as pronounced as for <code>co</code>.</p></li>
<li><p>The <code>o3</code> boxplot shows a relatively wide IQR, indicating moderate variability within the central 50% of the data. The median is slightly off-center, and the whiskers are slightly unequal, suggesting a slight asymmetry in the distribution. The absence of outliers indicates that <code>o3</code> values are spread consistently within the range, with no extreme deviations, leading to a stable variability overall.</p></li>
<li><p>The <code>so2</code> boxplot shows a narrow IQR, similar to <code>co</code> and <code>no2</code>, signifying a low variability in the central 50% of values. The short whiskers and presence of outliers up to 0.008 ppm suggest a concentrated distribution around the median, with occasional high values adding to overall variability.</p></li>
<li><p>The outliers in each of the pollutant may be attributed to factors like emissions from combustion, peak traffic periods, seasonal variations (holiday, non-holiday period), weather conditions like high humidity, natural events like wildfires or could possibly be anomalies in measurements. These would provide additional perspective while doing further analysis and best to retain them.</p></li>
</ul>
<p><strong>Summary mean/median of each measurements</strong></p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>skim_summary <span class="ot">&lt;-</span> data_wider <span class="sc">|&gt;</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>(pm25, pm10, so2, o3, no2, co) </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>skim_summary <span class="ot">&lt;-</span> skim_summary <span class="sc">|&gt;</span> </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(n_missing, numeric.hist, complete_rate))</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>skim_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">data_wider</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">2946</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">pm25</td>
<td style="text-align: right;">6.82</td>
<td style="text-align: right;">6.96</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2.67</td>
<td style="text-align: right;">4.96</td>
<td style="text-align: right;">8.60</td>
<td style="text-align: right;">63.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">pm10</td>
<td style="text-align: right;">19.83</td>
<td style="text-align: right;">17.85</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">9.66</td>
<td style="text-align: right;">14.88</td>
<td style="text-align: right;">23.32</td>
<td style="text-align: right;">188.09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">so2</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">o3</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">no2</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.07</td>
</tr>
<tr class="even">
<td style="text-align: left;">co</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">1.55</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Overall, <code>pm25</code> has an average concentration of 6.82 µg/m³, with a standard deviation of 6.96, indicating variability in measurements. The minimum value for <code>pm25</code> is 0.00 µg/m³, while the maximum reaches 63.01 µg/m³. Additionally, <code>pm10</code> shows a highest mean concentration at 19.83 µg/m³ and a wide range, with a maximum of 188.09 µg/m³. The other pollutants, such as <code>so2</code>, <code>o3</code>, <code>no2</code>, and <code>co</code>, show lower mean concentrations. Based on the max and min (p0 and p100 respectively) values for each pollutant, the values are with probable range.</p>
</section>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory data analysis</h2>
<!--
Make an exploratory analysis of the data, to learn if there is anything unusual or unexpected in the data. Your exploration needs to look at relationships between the different pollutants, and temporal patterns. 
-->
<section id="distribution-and-correlations" class="level4">
<h4 class="anchored" data-anchor-id="distribution-and-correlations">Distribution and Correlations</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggscatmat</span>(data_wider, <span class="at">columns=</span><span class="dv">7</span><span class="sc">:</span><span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>All five sensors <code>pm25</code>, <code>pm10</code>, <code>so2</code>, <code>no2</code>, and <code>co</code> exhibit right-skewed distributions, while <code>o3</code> shows a multimodal distribution. Additionally, there is a strong positive correlation between <code>pm25</code> and <code>co</code>, with a correlation coefficient of 0.79, and a moderate positive correlation between <code>no2</code> and <code>co</code>, with a coefficient of 0.65. While there are negative relationships between <code>o3</code> and <code>no2</code>, <code>o3</code> and <code>co</code> with correlations are -0.78 and -0.7.</p>
</section>
<section id="general-analysis---overview" class="level4">
<h4 class="anchored" data-anchor-id="general-analysis---overview">General Analysis - Overview</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#overview</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>alp_gee <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"pm25"</span>, <span class="st">"pm10"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>date_utc, <span class="at">y=</span>value, <span class="at">color=</span> parameter)) <span class="sc">+</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Overall, based on the hourly concentrations of <code>pm10</code> and <code>pm25</code>during July and August 2024 in Alphington and Geelong South, it is evident that PM₁₀ levels are almost higher than <code>pm25</code>.</p>
<p>Notably, <code>pm10</code> concentrations exceed 75 µg/m³ at times, with several instances reaching or surpassing 150 µg/m³, indicating significant variability. In contrast, <code>pm25</code> concentrations remain below 75 µg/m³ and exhibit less fluctuation, with a narrower range of variation compared to <code>pm10</code>.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>alp_gee <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span>(parameter <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"pm25"</span>, <span class="st">"pm10"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>date_utc, <span class="at">y=</span>value, <span class="at">color=</span> parameter)) <span class="sc">+</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Among the four parameters <code>co</code>, <code>no2</code>, <code>o3</code> and <code>so2</code> measured during July and August 2024 in Alphington and Geelong South, <code>co</code> stands out with the highest concentration and significant fluctuations, ranging from around 0.1 to as high as 1.5 ppm. This wide range indicates notable variability in <code>co</code> levels over time.</p>
<p>In contrast, <code>no2</code>, <code>o3</code> and <code>so2</code> concentrations are considerably lower, all remaining below 0.1 ppm throughout the period. Despite their lower levels, these parameters will be analyzed in more detail below to assess whether they show any noticeable fluctuations.</p>
</section>
<section id="detailed-parameter-analysis" class="level4">
<h4 class="anchored" data-anchor-id="detailed-parameter-analysis">Detailed Parameter Analysis</h4>
<section id="pm25" class="level5">
<h5 class="anchored" data-anchor-id="pm25">1. <strong><code>pm25</code></strong></h5>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>alp_gee <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">==</span> <span class="st">"pm25"</span>) <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>date_utc, <span class="at">y=</span>value, <span class="at">color=</span>location)) <span class="sc">+</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>location) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Hourly pm2.5 Concentration"</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"pm2.5"</span>)<span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="at">guide =</span> <span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><code>pm25</code> concentrations in both Alphington and Geelong South show similar levels on certain days, around 10 µg/m³.</p></li>
<li><p>Both locations have peaks at the beginning of July and August, though the highest concentrations in Alphington are generally higher than in Geelong South, reaching approximately 60 µg/m³ compared to around 40 µg/m³.</p></li>
<li><p>A more detailed look at the concentration levels in both locations is provided in the calendar plot below.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>aggregate_data <span class="ot">&lt;-</span> data_wider <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.Date</span>(date_utc)) <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(date, location) <span class="sc">|&gt;</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">c</span>(<span class="st">"pm25"</span>, <span class="st">"pm10"</span>, <span class="st">"so2"</span>, <span class="st">"o3"</span>, <span class="st">"no2"</span>, <span class="st">"co"</span>), mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>aggregate_data <span class="sc">|&gt;</span>  </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> pm25, <span class="at">color =</span> location)) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Daily Average pm2.5 Concentration"</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Concentration"</span>) <span class="sc">+</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Similar to the hourly concentrations, the daily average <code>pm25</code> concentrations in both locations reveal a clearer trend, with peaks at the beginning of each month followed by a gradual decrease.</p></li>
<li><p>Additionally, the average concentration in Alphington is consistently higher than in Geelong South.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>calendar <span class="ot">&lt;-</span>  alp_gee <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.Date</span>(date_utc),</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">hour =</span> <span class="fu">hour</span>(date_utc)) <span class="sc">|&gt;</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(date)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co">#"pm25" "pm10" "so2"  "o3"   "no2"  "co"</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># "Alphington" and "Geelong South" </span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>calendar <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">==</span> <span class="st">"pm25"</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span>   </span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>hour, <span class="at">y=</span>value,<span class="at">color=</span>location)) <span class="sc">+</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_calendar</span>(<span class="sc">~</span>date) <span class="sc">+</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">aspect.ratio =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Calendar of pm2.5 Concentration for Alphington &amp; Geelong South"</span>) <span class="sc">+</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>There is no clear seasonal pattern in <code>pm25</code> concentrations. However, during the first week of July and August, the concentrations fluctuate more widely compared to the rest.</p></li>
<li><p>Notably, on July 4, July 31, and August 3, <code>pm25</code> levels in Alphington are significantly higher than in Geelong South, ranging between 20 and 60 µg/m³, while Geelong South remains around or below 20 µg/m³.</p></li>
<li><p>In contrast, on August 1, Geelong South shows higher concentrations than in Alphington, with a peak of 40 µg/m³ compared to Alphington’s peak of around 20 µg/m³.</p></li>
</ul>
</section>
<section id="pm10" class="level5">
<h5 class="anchored" data-anchor-id="pm10">2. <strong><code>pm10</code></strong></h5>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>alp_gee <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">==</span> <span class="st">"pm10"</span>) <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>date_utc, <span class="at">y=</span>value, <span class="at">color=</span>location)) <span class="sc">+</span> </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>location) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Hourly pm10 Concentration"</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"pm10"</span>)<span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="at">guide =</span> <span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>There is missing data for Geelong South at the beginning of July. While <code>pm25</code> concentrations are generally higher in Alphington, <code>pm10</code> levels in Geelong South fluctuate more widely. Geelong South experiences peaks above 100 µg/m³, whereas the highest levels in Alphington are around 60 µg/m³.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>aggregate_data <span class="sc">|&gt;</span>  </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> pm10, <span class="at">color =</span> location)) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Daily Average pm10 Concentration"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Concentration"</span>) <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>There are different trends in the average daily <code>pm10</code> concentrations between the 2 locations at the beginning of July.</p></li>
<li><p>In Geelong South, concentrations increase from the start of the month, while in Alphington they decrease.</p></li>
<li><p>However, after mid-July, both locations follow a similar trend. One reason for this difference may be the missing data at the beginning of July in Geelong South.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>calendar <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">==</span> <span class="st">"pm10"</span>) <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span>   </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>hour, <span class="at">y=</span>value,<span class="at">color=</span>location)) <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_calendar</span>(<span class="sc">~</span>date) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">aspect.ratio =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Calendar of pm10 Concentration for Alphington &amp; Geelong South"</span>)<span class="sc">+</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>There is no clear seasonal pattern in <code>pm10</code> concentrations. Throughout July and August, levels in Geelong South are generally higher than those in Alphington.</p></li>
<li><p>Specifically, at the beginning of August, concentrations in Geelong South fluctuate over a wider range compared to Alphington. Additionally, there are some days when the highest levels occur around midnight.</p></li>
<li><p>Moreover, on August 18 and 22, for instance, the concentrations peak around 100 µg/m³, while daytime levels are significantly lower, averaging around 25 µg/m³ or below.</p></li>
</ul>
</section>
<section id="so2" class="level5">
<h5 class="anchored" data-anchor-id="so2">3. <strong><code>so2</code></strong></h5>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>alp_gee <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">==</span> <span class="st">"so2"</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>date_utc, <span class="at">y=</span>value, <span class="at">color=</span>location)) <span class="sc">+</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>location)<span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Hourly so2 Concentration"</span>,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"so2"</span>)<span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="at">guide =</span> <span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Most <code>so2</code> concentrations in both locations fall within the range of 0 to 0.001 ppm.</p></li>
<li><p>The highest levels in Geelong South exceed those in Alphington, with concentrations reaching above 0.002 ppm, while Alphington’s highest levels are at 0.002 ppm.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>aggregate_data <span class="sc">|&gt;</span>  </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> so2, <span class="at">color =</span> location)) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Daily Average so2 Concentration"</span>,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Concentration"</span>) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>There are distinct trends in the average daily <code>so2</code> concentrations between the two locations.</p></li>
<li><p>Geelong experiences peaks at the beginning of both July and August, while levels in Alphington show less fluctuation and gradually decrease after mid-August.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>calendar <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">==</span> <span class="st">"so2"</span>) <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span>   </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>hour, <span class="at">y=</span>value,<span class="at">color=</span>location)) <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_calendar</span>(<span class="sc">~</span>date) <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">aspect.ratio =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Calendar of so2 Concentration for Alphington &amp; Geelong South"</span>)<span class="sc">+</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>There is no clear seasonal pattern in the calendar plot, and the <code>so2</code> concentrations fluctuate within a narrow range on most days in both locations.</p></li>
<li><p>However, a few days show significant differences between the two locations, indicating short-term increases in concentration.</p></li>
<li><p>For instance, on July 3 and August 12, <code>so2</code> levels in Geelong South peak much higher than in Alphington. On July 3, the peak occurs around midnight, reaching approximately 0.005 ppm, while on August 12, the concentration peaks in the early morning at around 0.008 ppm.</p></li>
</ul>
</section>
<section id="o3" class="level5">
<h5 class="anchored" data-anchor-id="o3">4. <strong><code>o3</code></strong></h5>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>alp_gee <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">==</span> <span class="st">"o3"</span>) <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>date_utc, <span class="at">y=</span>value, <span class="at">color=</span>location)) <span class="sc">+</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>location)<span class="sc">+</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Hourly o3 Concentration"</span>,</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"o3"</span>)<span class="sc">+</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="at">guide =</span> <span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><code>o3</code> concentrations at both Alphington and Geelong South range from approximately 0.003 ppm to over 0.03 ppm, indicating relatively low ozone levels overall.</p></li>
<li><p>The scatterplot succinctly captures the hourly fluctuations within each day. This could to attributed to daily cycles of traffic patterns or weather conditions.</p></li>
<li><p>Both Alphington and Geelong South have similar distributions and ranges of <code>o3</code>, suggesting comparable air quality with respect to ozone in both locations.</p></li>
<li><p>The data points are within a tight range, with no extreme spikes, indicating stable ozone levels that are not prone to sudden increases.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>aggregate_data <span class="sc">|&gt;</span>  </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> o3, <span class="at">color =</span> location)) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Daily Average o3 Concentration"</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Concentration"</span>) <span class="sc">+</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>The above plot shows the daily average concentration for Alphington and Geelong South, with both locations displaying a similar trend.</p></li>
<li><p><code>o3</code> levels drop to their lowest point in July, then rise, dip slightly around mid-August, and increase again toward the end of August.</p></li>
<li><p>On average, Geelong South generally has higher <code>o3</code> concentrations compared to Alphington, particularly in early July and from mid-August onward.</p></li>
<li><p>Despite minor differences, the parallel LOESS curves suggest that both locations experience similar seasonal or environmental influences on <code>o3</code> levels.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>calendar <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">==</span> <span class="st">"o3"</span>) <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span>   </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>hour, <span class="at">y=</span>value,<span class="at">color=</span>location)) <span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_calendar</span>(<span class="sc">~</span>date) <span class="sc">+</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">aspect.ratio =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Calendar of o3 Concentration for Alphington &amp; Geelong South"</span>)<span class="sc">+</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Most days, both locations follow a daily cycle, where <code>o3</code> levels rise in the morning, peaking at midday and declining by evening.</p></li>
<li><p>Geelong South consistently shows higher peaks compared to Alphington, suggesting elevated <code>o3</code> levels overall.</p></li>
<li><p>July 3rd, 4th, 5th, and 31st: Geelong South has sharp peaks with minimal variation in Alphington, likely due to localized factors.</p></li>
<li><p>There is an unusual increasing trend on July 19th, instead of the usual decreasing trend in the evenings for both Alphington and Geelong South.</p></li>
<li><p>July 15, August 26, 30, 31: The <code>o3</code> levels seem to be consistently high at around 0.03 ppm with minimal variations throughout the day.</p></li>
<li><p>Weekend peaks are frequently as high as those on weekdays, and the overall patterns remain largely consistent across all days, indicating that ozone levels are influenced by sustained factors, regardless of the day of the week.</p></li>
</ul>
</section>
<section id="no2" class="level5">
<h5 class="anchored" data-anchor-id="no2">5. <strong><code>no2</code></strong></h5>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>alp_gee <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">==</span> <span class="st">"no2"</span>) <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>date_utc, <span class="at">y=</span>value, <span class="at">color=</span>location)) <span class="sc">+</span> </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>location)<span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Hourly no2 Concentration"</span>,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"no2"</span>)<span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="at">guide =</span> <span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>There is data missing for Geelong South for a significant part of August.</p></li>
<li><p>The variations of <code>no2</code> at both Alphington and Geelong South are similar, ranging from 0.00 ppm to 0.04 ppm for most time although the highest concentrations in Alphington are generally lower than in Geelong South, reaching approximately 0.04 ppm compared to over 0.06 ppm.</p></li>
<li><p><code>no2</code> concentrations remain stable over time, with no clear seasonal or time-dependent trends.</p></li>
<li><p>There are daily variations, but no consistent pattern of peaks or troughs is apparent in the scatterplot.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>aggregate_data <span class="sc">|&gt;</span>  </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> no2, <span class="at">color =</span> location)) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Daily Average no2 Concentration"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Concentration"</span>) <span class="sc">+</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>The average levels of <code>no2</code> concentration appears to follow a similar trend at both Alphington and Geelong South. Both peak at the start of July with concentration over 0.015 ppm and dip mid July before rising again in early August before declining again.</p></li>
<li><p>Average <code>no2</code> levels are slightly higher at Alphington until late July, likely due to its proximity to the city and increased traffic, which could account for the elevated <code>no2</code> levels compared to Geelong South.</p></li>
<li><p>With data missing for much of August at Geelong South, we might expect a similar downward trend as observed at Alphington. However, further investigation is necessary to confirm this assumption.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>calendar <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">==</span> <span class="st">"no2"</span>) <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span>   </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>hour, <span class="at">y=</span>value,<span class="at">color=</span>location)) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_calendar</span>(<span class="sc">~</span>date) <span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">aspect.ratio =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Calendar of no2 Concentration for Alphington &amp; Geelong South"</span>)<span class="sc">+</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>There is no clear seasonal pattern in <code>no2</code> concentrations, but the first week of July shows wider fluctuations compared to other days.</p></li>
<li><p>Notably, on July 3, <code>no2</code> levels in Geelong South peak twice, mid-day and late night, reaching around 0.04 ppm and above 0.06 ppm, higher than Alphington’s peak of 0.03 ppm in the morning.</p></li>
<li><p>On July 4, Geelong South shows a reverse trend, with levels decreasing from around 0.03 ppm early in the day before rising again at night, whereas in Alphington, <code>no2</code> levels increase and peak later in the morning, then decline from noon.</p></li>
</ul>
</section>
<section id="co" class="level5">
<h5 class="anchored" data-anchor-id="co">6. <strong><code>co</code></strong></h5>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>alp_gee <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">==</span> <span class="st">"co"</span>) <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>date_utc, <span class="at">y=</span>value, <span class="at">color=</span>location)) <span class="sc">+</span> </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>location)<span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Hourly co Concentration"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"co"</span>)<span class="sc">+</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="at">guide =</span> <span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><code>co</code> levels follow a similar pattern over the observed period at both locations, with higher concentrations at the start of each month that gradually stabilize by mid-month.</p></li>
<li><p>In Alphington <code>co</code> levels are higher, ranging up to 1.5 ppm, with multiple spikes exceeding 1.0 ppm, particularly in early July and early August. In Geelong <code>co</code> levels range from 0.0 to around 1.2 ppm, with occasional peaks above 0.5 ppm, indicating some variability.</p></li>
<li><p>While, Alphington shows more frequent and intense spikes, likely due to urban sources such as traffic. Geelong South has overall lower <code>co</code> levels, with less frequent and smaller peaks, suggesting fewer or less intense sources.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>aggregate_data <span class="sc">|&gt;</span>  </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> co, <span class="at">color =</span> location)) <span class="sc">+</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Daily Average co Concentration"</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Concentration"</span>) <span class="sc">+</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Both locations display a decline in average <code>co</code> levels from early July, reaching a low around late August. The steepest decline is observed in the first half of July, particularly at Alphington.</p></li>
<li><p>There is a noticeable peak at the start of each month, with <code>co</code> levels higher in early July and early August before tapering off towards the middle and end of the month.</p></li>
<li><p>Alphington starts with a higher <code>co</code> concentration, peaking near 0.6 ppm, which steadily decreases over time. Its levels remain higher than Geelong South’s until late July, when they begin to converge towards end of August.</p></li>
<li><p>Geelong South maintains generally lower <code>co</code> concentrations, peaking around 0.3 ppm in early July and declining more gradually. This trend indicates consistently lower <code>co</code> pollution in comparison to Alphington.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>calendar <span class="sc">|&gt;</span> <span class="fu">filter</span>(parameter <span class="sc">==</span> <span class="st">"co"</span>) <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span>   </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>hour, <span class="at">y=</span>value,<span class="at">color=</span>location)) <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_calendar</span>(<span class="sc">~</span>date) <span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">aspect.ratio =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Calendar of co Concentration for Alphington &amp; Geelong South"</span>)<span class="sc">+</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Both locations show <code>co</code> peaks, mainly in the morning, likely due to traffic emissions. Alphington consistently has higher peaks than Geelong South.</p></li>
<li><p>Alphington frequently surpasses 0.5 ppm, with some peaks over 1.0 ppm. Geelong South generally stays below 0.5 ppm and exhibits fewer fluctuations.</p></li>
<li><p>High Spikes in Early July and August, Alphington shows significant spikes on July 2nd to 4th, and August 3rd-4th, reaching over 1.0 ppm, not seen at Geelong South except on July 3rd. Although, most high spikes but in reduced levels for Geelong appear around the same time.</p></li>
<li><p>Low Variability in late August, both locations show reduced <code>co</code> levels and minimal fluctuations, possibly due to improved dispersion conditions. Similar trend can be observed in July, from 19th to 26th, although there is data missing on July 19th.</p></li>
<li><p>While weekdays have more pronounced peaks, both locations follow a similar pattern across all days, with Alphington displaying consistently higher <code>co</code> due to its urban environment.</p></li>
</ul>
</section>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>Overall, the sensors in Alphington and Geelong South do not consistently report the same values:</p>
<ul>
<li><p><code>pm25</code> concentrations in both locations are generally below 20 µg/m³ on most days, which is within the safe threshold of 25 µg/m³. However, Alphington generally records more higher values, with peaks reaching up to 60 µg/m³ compared to Geelong South’s maximum of 40 µg/m³.</p></li>
<li><p><code>pm10</code> concentrations in both locations mostly remain below 20 µg/m³, which is well under the recommended limit of 50 µg/m³. However, Geelong South frequently experiences higher values, exceeding 50 µg/m³ and even surpassing 100 µg/m³, whereas Alphington’s peak levels reach only around 60 µg/m³.</p></li>
<li><p><code>so2</code> concentrations typically range from 0 to 0.001 ppm in both locations, staying within the safe range of 0 to 0.005 ppm. However, Geelong South occasionally experiences spikes with higher levels, reaching between 0.006 and 0.008 ppm.</p></li>
<li><p><code>o3</code> concentrations at Alphington and Geelong South range from approximately 0 ppm to over 0.03 ppm, with both locations displaying similar trends in average levels. Both remain within the safe limit of 0.07 ppm for 8-hour exposure. However, Geelong South tends to show higher levels, particularly in the morning.</p></li>
<li><p><code>no2</code> concentrations typically range from 0.00 ppm to 0.04 ppm in both locations, remaining below the safe limit of 0.08 ppm for one-hour exposure. Only on July 3, Geelong South recorded a high peak of 0.06 ppm at night. Due to missing data for Geelong South in August, trends during this period are uncertain, but both locations exhibited similar daily average values in July.</p></li>
<li><p><code>co</code> concentrations in both locations peak at the start of each month, with Alphington consistently higher, reaching up to 1-1.5 ppm. Despite these peaks, both locations remain well below the safe limit of 6 ppm for 8-hour exposure.</p></li>
</ul>
<p>In conclusion, although we expect that Alphington will be more polluted than Geelong South due to its proximity to the Melbourne CBD, which is more crowded, Geelong South still faces more frequent and significant spikes in <code>pm10</code> and <code>so2</code>. This indicates a potential for health risks in that area as well. The consistently higher pollution levels of the other pollutants in Alphington suggest urban influences, likely from traffic and other sources. Further, there doesn’t seem to appear a different trend on weekdays compared to weekends. The variations and patterns are quite similar on all days of the week. In addition, the expectation of positive correlations among pollutants was partially met, with strong positive correlations between <code>pm25</code> and <code>co</code> (0.79), and moderate positive correlations between <code>no2</code> and <code>co</code> (0.65). However, unexpected negative correlations were observed between <code>o3</code> and both <code>no2</code> (-0.78) and <code>co</code> (-0.7), which diverges from the anticipated trend, suggesting a more complex relationship involving ozone.</p>
</section>
<section id="generative-ai-analysis" class="level2">
<h2 class="anchored" data-anchor-id="generative-ai-analysis">Generative AI analysis</h2>
<p>The link to our use of ChatGPT for help on this project are: https://chatgpt.com/share/67085ceb-35e8-800f-98d3-c5eb125df5d2 https://chatgpt.com/share/6709bfab-03e0-8005-a3ba-a1853db0387e</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li>OpenAQ. (n.d.). Explore Open Air Quality. Retrieved from https://explore.openaq.org/#1.2/13.8/40</li>
<li>World Health Organization. (n.d.). Types of Pollutants. Retrieved from https://www.who.int/teams/environment-climate-change-and-health/air-quality-and-health/health-impacts/types-of-pollutants</li>
<li>NSW Government. (n.d.). Air Quality Categories - Health Advice. Retrieved from https://www.airquality.nsw.gov.au/health-advice/air-quality-categories</li>
<li>OpenAQ. (2022). Open Air Quality Data Global Landscape 2022. Retrieved from https://documents.openaq.org/reports/Open+Air+Quality+Data+Global+Landscape+2022.pdf</li>
<li>OpenAQ. (2020). Open Air Quality Data Global State of Play 2020. Retrieved from https://documents.openaq.org/reports/Open+Air+Quality+Data+Global+State+of+Play+2020.pdf</li>
<li>Clean Air Fund. (n.d.). Countries Failing to Report Data on Air Pollution. Retrieved from https://www.cleanairfund.org/news-item/countries-failing-data-on-air-pollution/</li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>