{
  "hash": "31801a45448fc208c24a3d365a6f1af9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The Relationship Between Weather and Atmospheric Pollutants\"\nauthor: \"Travis Rutledge and Pooja Rajendran Raju\"\ndate: \"Nov 28, 2024\"\noutput: \n  html:\n    css: \"assignment.css\"\nbibliography: references.bib\ncategories: [Group Project]\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n## Introduction\n\nThe purpose of this report is to explore the relationship between air pollution and weather in Australia. Four research questions will be addressed: \n\n1. Do higher temperatures lead to increase in the formation of ground-level ozone?\n2. Does rain and snow wash out particular matter and water-soluble gases from the air?\n3. Do high pressure systems often lead to stagnant air trapping pollutants?\n4. Does sunlight drive photochemical reactions that form secondary pollutants like ozone? \n\nTo answer these questions, data was pulled, cleaned, compiled, and analysed. The following sections will describe the data and then answer the research questions using visual inference and other analytical approaches. \n\n## Data Description\n\n### Data Pull\nData were pulled from two data sources. First, air pollution data was pulled from OpenAQ [@openAQ] using the airpurifyr R package [@airpurifyr]. OpenAQ is the world's largest open-source air quality data platform. Second, weather data was pulled from SILO [@SILO] using the weatherOz R package [@weatherOz]. SILO is a database of Australian climate data from 1889 to the present. After air pollution and weather data were pulled, the data sets were joined based on date. \n\nData was pulled from Alphington and Footscray in Melbourne, Victoria. These locations were chosen because they had the most amount of data available over a full year. Our team originally wanted to pull data from both Melbourne and Sydney to be consistent with our analysis between the two cities, but that proved not possible because there was not a full year's worth available for the same time period. So, our solution was to focus on pulling data from locations that had the most amount of data over the same time period. Ultimately, the best solution was to pull from Alphington and Footscray for 2022. \n\nEach observation in the air pollution data set was the value of a given air pollutant for a specific hour of a specific day. For the purpose of our analysis, these hourly data records were aggregated to daily records by calculating the average pollution values for each day. The weather data was already at a daily level, so no aggregation was necessary. Data sets were then saved as .rds files. \n\nThe following code was used to pull the data:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#2022 Alphington\nalphington2022 <- get_measurements_for_location(country = \"AU\", \n    location = \"Alphington\",\n    date_from = as.Date(\"2022-01-01\"),\n    date_to = as.Date(\"2022-12-31\")) %>%\n    mutate(date = as.Date(date_utc)) %>%\n  group_by(date, parameter, location, unit, lat, long, country) %>%\n  mutate(avg_value = mean(value, na.rm = TRUE)) %>%\n  distinct(date, parameter, location, unit, lat, long, country, avg_value) %>%\n  mutate(avg_value = format(avg_value, scientific = FALSE),\n        lat = round(lat, 2), long = round(long, 2)) \n\n#2022 Footscray\nfootscray2022 <- get_measurements_for_location(country = \"AU\", \n    location = \"Footscray\",\n    date_from = as.Date(\"2022-01-01\"),\n    date_to = as.Date(\"2022-12-31\")) %>%\n  mutate(date = as.Date(date_utc)) %>%\n  group_by(date, parameter, location, unit, lat, long, country) %>%\n  mutate(avg_value = mean(value, na.rm = TRUE)) %>%\n  distinct(date, parameter, location, unit, lat, long, country, avg_value) %>%\n  mutate(avg_value = format(avg_value, scientific = FALSE),\n        lat = round(lat, 2), long = round(long, 2)) \n\n#union the data\nair_data <- rbind(alphington2022,footscray2022) |> \n  mutate(date = as.Date(date))\n\n#save air pollution data as RDS\nsaveRDS(air_data, file = \"airdata.rds\")\n\n#pull silo data\nsilo <- get_data_drill(\n  latitude = -38,\n  longitude = 145,\n  start_date = \"20220101\",\n  end_date = \"20221231\",\n  values = c(\n         \"max_temp\",\n         \"min_temp\",\n         \"rain\", \n         \"mslp\",\n         \"vp\",\n         \"vp_deficit\",\n         \"radiation\"\n     )\n ) %>% rename(lat = latitude, long = longitude) \n\n#save silo data as RDS\nsaveRDS(silo, file = \"silo.rds\")\n```\n:::\n\n\n### Data Cleaning and Joining\n\nAfter the data was pulled, they were cleaned, made into a tidy format, and joined together. This involved removing unnecessary variables and using a left join that prioritized the air pollution data. The following code was used for this process:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nair_data <- readRDS(file = \"airdata.rds\")\nsilo <- readRDS(file = \"silo.rds\")\njoin <- left_join(air_data, silo, by = c(\"date\"))\n\n#filter out unnecessary variables\nair_and_weather_data <- join %>%\n  ungroup() |>   \n  select(-country, -lat.x, -long.x, -long.y, -lat.y, -extracted, -year, \n         -air_tmax_source, -air_tmin_source, -rainfall_source, -elev_m,\n         -mslp_source, -radiation_source, -vp_deficit_source, -vp_source)\n\nwrite.csv(air_and_weather_data, file = \"data/air_and_weather_data.csv\", row.names = FALSE)\n```\n:::\n\n\n### Data Definitions \n\nThe dataset contains 14 variables and 4261 observations. \n\nThe following are the variables used in this analysis:\n\n| Variable    | Description                                | Source\n|-------------|--------------------------------------------|-----------\n| date        | Date when the data was recorded            | OpenAQ and SILO\n| parameter   | Pollutant parameters (ex: pm25, pm10, so3) | OpenAQ\n| location    | Location name                              | OpenAQ\n| unit        | Unit of measurement                        | OpenAQ\n| avg_value   | Measurement of parameter for that day      | OpenAQ\n| month       | Month when the data was recorded           | SILO\n| day         | Day when the data was recorded             | SILO\n| air_tmax    | The maximum temperature for the day in C   | SILO\n| air_tmin    | The minimum temperature for the day in C   | SILO\n| mslp        | Mean sea level pressure in hPa             | SILO\n| radiation   | Solar exposure in $MJ/m^2$                 | SILO\n| rainfall    | Daily rainfall in mm                       | SILO\n| vp          | Vapour pressure in hPa                     | SILO\n| vp_deficit  | Vapour pressure deficit in hPa             | SILO\n\n### Data Screening \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nvis_dat(air_and_weather_data)\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nUnderstanding the composition of variable types in the dataset using ‘vis_dat’. Here, the dataset primarily comprises of character type variables, date type variables, numeric and integer variables. \n\n**Checking for Duplicate Rows**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Detecting duplicate rows\nsum(duplicated(air_and_weather_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nThere are no duplicate rows observed in the dataset. \n\n**Evaluating the Structure of Data**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nglimpse(air_and_weather_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 4,261\nColumns: 14\n$ date       <date> 2022-12-31, 2022-12-30, 2022-12-29, 20…\n$ parameter  <chr> \"pm25\", \"pm25\", \"pm25\", \"pm25\", \"pm25\",…\n$ location   <chr> \"Alphington\", \"Alphington\", \"Alphington…\n$ unit       <chr> \"µg/m³\", \"µg/m³\", \"µg/m³\", \"µg/m³\", \"µg…\n$ avg_value  <chr> \"9.9\", \"11\", \"5.8\", \"6.2\", \"6.4\", \"12\",…\n$ month      <dbl> 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,…\n$ day        <int> 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,…\n$ air_tmax   <dbl> 29, 26, 20, 26, 38, 29, 30, 22, 22, 24,…\n$ air_tmin   <dbl> 17.2, 12.6, 12.9, 24.5, 16.9, 16.3, 11.…\n$ mslp       <dbl> 1014, 1016, 1019, 1008, 1018, 1017, 101…\n$ radiation  <dbl> 29.8, 32.2, 18.8, 4.7, 31.7, 29.6, 32.2…\n$ rainfall   <dbl> 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.4,…\n$ vp         <dbl> 18.6, 15.3, 10.4, 18.4, 20.4, 17.9, 15.…\n$ vp_deficit <dbl> 15.3, 12.1, 10.3, 15.2, 28.7, 15.8, 17.…\n```\n\n\n:::\n:::\n\nAll variables are of appropriate data types apart from `avg_value` which is currently a `chr` variable and needs to be converted to `dbl`. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nair_and_weather_data$avg_value <- as.numeric(air_and_weather_data$avg_value)\n```\n:::\n\n\n\n### Checking Missing Data \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#Converting data to wider form to explore missingness \ndata_wider <- air_and_weather_data |> \n             select(-unit)  |>\n           pivot_wider(names_from = parameter,\n                       values_from = avg_value)\n#write.csv(data_wider, file = \"data/data_wider.csv\", row.names = FALSE)\n\n# Calculating the missing percentage\nmissing_summary <- data_wider |> \n  summarise(across(everything(), ~ sum(is.na(.)) / n() *100)) |> \n  pivot_longer(cols = everything(),\n               names_to = \"variable\", \n               values_to = \"missing_percentage\") \n\n#Plotting the missing percentage for each variable\nggplot(missing_summary, \n       aes(x = reorder(variable,-missing_percentage), \n           y = missing_percentage))  +\n  geom_segment(aes(xend = variable, yend = 0), color = \"blue\") +\n  geom_point(size = 2, color = \"black\") +\n  coord_flip() +\n  labs(title = \"Missing Data Percentage\",\n       x = \"Pollutant\",\n       y = \"Missing Percentage (%)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nBased on the above plot, we can infer that the data is relatively complete with minimal missing values. Parameters `no2`, `co`, `pm10` and `pm25` have missing values less than 5%. \n\n\n**Specific Date Analysis of Missing Data**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nmissing_specific <- data_wider |>\n  as_tsibble(key = location, index = date)\n\ncount_gaps(missing_specific)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 4\n  location   .from      .to           .n\n  <chr>      <date>     <date>     <int>\n1 Alphington 2022-02-06 2022-02-06     1\n2 Alphington 2022-03-23 2022-03-24     2\n3 Footscray  2022-02-06 2022-02-06     1\n4 Footscray  2022-03-23 2022-03-24     2\n5 Footscray  2022-09-25 2022-09-25     1\n6 Footscray  2022-11-23 2022-11-23     1\n7 Footscray  2022-12-18 2022-12-18     1\n```\n\n\n:::\n:::\n\n\nBetween February and December 2022, both Alphington and Footscray\nhad overlapping gaps on February 6th and from March 23rd to March 24th, while Footscray experienced unique missing data on the other three days:  September 25th, November 23rd, and December 18th.\n\n\n<!--\n\nDescription of data, number of observations, variables and types, any cleaning procedures that might be needed or transformation. Data download code. (1pt)\n\nDescription of the variables, as organised into tidy form, nicely formatted as a table. Detailed and concise explanation of data being analysed with a comprehensive overview of the methods that might be needed to check and clean it, including reasons.\n-->\n\n\n## Relationship 1\n\n_**Higher temperatures can increase the formation of ground-level ozone**_ \n\nThe current research question explores whether higher temperatures drive the formation of ground-level ozone, a secondary pollutant influenced by atmospheric conditions. This analysis focuses on ozone (O3) levels, examining how variations in daily maximum and minimum temperatures (measured in degrees Celsius) relate to ozone concentrations. The following section investigates the correlation between temperature and ozone, aiming to understand the extent to which warmer conditions may promote ozone formation.\n\n**Evaluating Monthly Temperature Variation**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ndata_wider$month <- as.factor(data_wider$month)\n\n# Max Daily Temp\np1 <- ggplot(data_wider, aes(x=month, y=air_tmax)) +\n  geom_violin(draw_quantiles=c(0.25, 0.5, 0.75), fill= \"#56B4E9\") +\n  labs(x = \"Month\", y = \"Max Daily Temp (°C)\") + \n  theme_minimal()\n  \n\n# Min Daily Temp\np2 <- ggplot(data_wider, aes(x=month, y=air_tmin)) +\n  geom_violin(draw_quantiles=c(0.25, 0.5, 0.75), fill= \"#56B4E9\") +\n  labs(x = \"Month\", y = \"Min Daily Temp (°C)\") +\n  theme_minimal() \n\np1/p2\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- The violin plot provides context on the monthly maximum and minimum temperature distribution for Melbourne. Both maximum and minimum daily temperatures are highest during the summer months (December to February), especially in January, while the winter months (June to August) experience the lowest and most stable temperatures. \n- April and October show moderate temperature variability, serving as transitional months. Overall, summer and early autumn months are warmer, so if higher temperatures increase the formation of ground-level ozone, elevated ozone levels should be more apparent in these months. In contrast, winter months, with their consistently lower temperatures, would likely see reduced ozone formation.\n\n**Evaluating Average Variation of Ozone compared to Max and Min Temperature**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Average tmax, tmin, and O3 levels\ntemp_oz_summary <- data_wider %>%\n  group_by(month) %>%\n  summarise(avg_tmax = mean(air_tmax, na.rm = TRUE),\n            avg_tmin = mean(air_tmin, na.rm = TRUE),\n            avg_o3 = mean(o3, na.rm = TRUE))\n\n\nggplot(temp_oz_summary, aes(x = month)) +\n  geom_line(aes(y = avg_tmax, \n                color = \"Max Temperature (°C)\", group = 1), size = 1.2) + \n  geom_line(aes(y = avg_tmin, \n                color = \"Min Temperature (°C)\", group = 1), size = 1.2) +                 geom_line(aes(y = avg_o3 * 1000, \n                color = \"Ozone (O3 in ppm)\", group = 1), size = 1.2) +                    scale_y_continuous(name = \"Temperature (°C)\", \n                     sec.axis = sec_axis(~./1000, name = \"Ozone (ppm)\")) +  \n  labs(x = \"Month\", \n       title = \"Average Max Temp, Min Temp, and Ozone Levels Over 12 Months\") +\n  scale_color_manual(values = c(\"Max Temperature (°C)\" = \"blue\", \n                                \"Min Temperature (°C)\" = \"green\",\n                                \"Ozone (O3 in ppm)\" = \"red\")) +\n  theme_minimal() +\n  theme(legend.title = element_blank())  \n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- These line graphs show the average maximum temperature, minimum temperature, and ozone levels across each month. The maximum and minimum temperatures follow a typical seasonal pattern, as observed in the earlier violin plots. \n- Ozone levels display a clear seasonal pattern aligned with temperature, peaking during the summer months (December to February) when both maximum and minimum daily temperatures are highest. This supports the expectation that higher temperatures facilitate ground-level ozone formation. Ozone levels remain relatively elevated in March before declining as temperatures start to drop in autumn. \n- During the winter months (June to August), ozone levels dip to their lowest, particularly in July, which aligns with the coldest temperatures of the year.\n- However, there are unexpected ozone peaks in June and September, which do not correspond with high temperatures. These anomalies suggest that factors such as high-pressure systems or local emissions may occasionally cause ozone levels to rise independently of temperature, particularly during transitional or atypical weather periods.\n\n**Examining Relationships Using Scatterplots**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# air_tmax vs. O3\np3 <- ggplot(data_wider, aes(y = o3, x = air_tmax)) +\n  geom_point(alpha = 0.5, color = \"blue\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkblue\") +\n  labs(title = \"Max Temperature vs Ozone\",\n       y = \"Ozone (ppm)\",\n       x = \"Max Temperature (°C)\") +\n  theme_minimal()\n\n# air_tmin vs. O3\np4 <- ggplot(data_wider, aes(y = o3, x = air_tmin)) +\n  geom_point(alpha = 0.5, color = \"red\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkred\") +\n  labs(title = \"Min Temperature vs Ozone\",\n       y = \"Ozone (ppm)\",\n       x = \"Min Temperature (°C)\") +\n  theme_minimal()\n\n\ngrid.arrange(p3, p4, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- Based on the scatter plots the following observations can be made: \n- There is a moderately positive relationship between maximum temperature and ozone, indicated by the steeper slope and tighter clustering of points around the trend line. This suggests that as daily maximum temperatures rise, ozone levels tend to increase.\n- Similarly, there is a positive relationship between minimum temperature and ozone, though it appears slightly weaker based on the lower gradient of the trend line and more dispersed points around it. This indicates that while warmer minimum temperatures are also associated with higher ozone levels, the effect is less pronounced than for maximum temperatures.\n- Overall, both maximum and minimum temperature trends provide evidence that temperature  plays a key role in ozone formation. Further analysis through linear modeling could help quantify these relationships more precisely.\n\n**Evaluating How The Daily Temperature Difference Affects Ozone Formation** \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Daily temperature range (tmax - tmin)\ndata_wider$temperature_range <- data_wider$air_tmax - data_wider$air_tmin\n\n# Ozone vs Temperature Range\nggplot(data_wider, aes(x = temperature_range, y = o3)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"green\") +\n  labs(title = \"Ozone vs Temperature Range (tmax - tmin)\",\n       x = \"Temperature Range (°C)\", y = \"Ozone (ppm)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- There is a slight tendency for ozone levels to increase as the daily temperature range grows, but the relationship is weak, as indicated by the nearly flat trend line.\n- This minimal increase suggests that while a larger temperature range might have some influence, it is not a strong determinant of ozone formation.\n- Overall, absolute temperatures (highs or lows) are more important for ozone formation than the daily difference between maximum and minimum temperatures.\n\n### Linear Models\n\n1. **Linear Modeling of Ozone with Max Temperature**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nlm_tmax <- lm(o3 ~ air_tmax, data = data_wider)\n\nsummary(lm_tmax)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = o3 ~ air_tmax, data = data_wider)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.015001 -0.003620 -0.000515  0.003845  0.016662 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 5.59e-03   7.37e-04    7.59    1e-13 ***\nair_tmax    4.59e-04   3.58e-05   12.83   <2e-16 ***\n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0055 on 719 degrees of freedom\nMultiple R-squared:  0.186,\tAdjusted R-squared:  0.185 \nF-statistic:  165 on 1 and 719 DF,  p-value: <2e-16\n```\n\n\n:::\n:::\n\n\n- The linear model shows a statistically significant positive relationship between maximum temperature and ozone levels: for each 1°C increase in maximum temperature, ozone levels increase by an estimated 0.000459 ppm. \n- With extremely low p-values for both the intercept and slope, the model confirms that maximum temperature is a highly significant predictor of ozone levels. Additionally, the F-statistic p-value is far below the 0.01 threshold, indicating very strong overall model significance. \n- However, the model’s R-squared value (0.186) suggests that maximum temperature explains only 18.6% of the variation in ozone levels, indicating that other factors also influence ozone formation.\n\n2. **Linear Modeling of Ozone with Min Temperature**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nlm_tmin <- lm(o3 ~ air_tmin, data = data_wider)\n\nsummary(lm_tmin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = o3 ~ air_tmin, data = data_wider)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.014985 -0.003807 -0.000673  0.003733  0.021601 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.009728   0.000555   17.52   <2e-16 ***\nair_tmin    0.000454   0.000047    9.65   <2e-16 ***\n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0057 on 719 degrees of freedom\nMultiple R-squared:  0.115,\tAdjusted R-squared:  0.113 \nF-statistic: 93.2 on 1 and 719 DF,  p-value: <2e-16\n```\n\n\n:::\n:::\n\n\n- The linear model shows a statistically significant positive relationship between minimum temperature and ozone levels: for each 1°C increase in minimum temperature, ozone levels increase by an estimated 0.000454 ppm.\n- With extremely low p-values for both the intercept and slope, the model confirms that minimum temperature is a highly significant predictor of ozone levels. Additionally, the F-statistic p-value is far below the 0.01 threshold, indicating very strong overall model significance. \n- However, the model’s R-squared value (0.115) suggests that minimum temperature explains only 11.5% of the variation in ozone levels, indicating that other factors also influence ozone formation.\n\n### Seasonal Evaluation\n\n**Seasonal Overview**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ndata_wider <- data_wider %>%\n  mutate(month = factor(month, levels = 1:12, labels = c(\"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", \"Jun\", \n                                                         \"Jul\", \"Aug\", \"Sep\", \"Oct\", \"Nov\", \"Dec\")),\n         season = case_when(\n           month %in% c(\"Jan\", \"Feb\", \"Dec\") ~ \"Summer\",\n           month %in% c(\"Mar\", \"Apr\", \"May\") ~ \"Autumn\",\n           month %in% c(\"Jun\", \"Jul\", \"Aug\") ~ \"Winter\",\n           month %in% c(\"Sep\", \"Oct\", \"Nov\") ~ \"Spring\"\n         ))\n\nggplot(data_wider, aes(x = month)) +\n  geom_smooth(aes(y = air_tmax, group = 1), method = \"loess\", span = 0.7, se = FALSE, color = \"blue\", size = 1.2) +\n  geom_smooth(aes(y = air_tmin, group = 1), method = \"loess\", span = 0.7, se = FALSE, color = \"green\", size = 1.2) +\n  geom_smooth(aes(y = o3 * 1000, group = 1), method = \"loess\", span = 0.7, se = FALSE, color = \"red\", size = 1.2) +\n  facet_wrap(~ season, ncol = 2, scales = \"free_x\") +\n  scale_y_continuous(name = \"Temperature (°C)\", \n                     sec.axis = sec_axis(~./1000, name = \"Ozone (ppm)\")) +\n  labs(title = \"Seasonal Comparison of Temperature and Ozone Levels\",\n       x = \"Month\", y = \"Temperature (°C)\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(hjust = 1),\n        legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- The above plot illustrates a strong seasonal pattern where ozone levels closely follow maximum temperature trends. \n- **Summer** - Summer has the highest ozone levels, aligning with the warmest temperatures. Maximum and minimum temperatures are high and stable. Ozone levels peak in January, followed closely by December, and decrease in February.\n- **Autumn** - Autumn shows a gradual decline in both temperatures and ozone levels, contrasting with the elevated levels seen in summer. Both maximum and minimum temperatures decline steadily. Ozone levels also decrease, following the cooling trend.\n- **Winter** - Winter has the lowest temperatures and ozone levels, emphasizing a strong seasonal effect on ozone reduction.Temperatures reach their lowest, with both maximum and minimum values consistently low. Ozone levels are at their lowest, dipping particularly in July.\n- **Spring** - Spring mirrors autumn as a transitional season, but with an upward trend in both temperature and ozone, leading into the high summer levels. Temperatures begin to rise gradually. Ozone levels increase as temperatures warm, reaching relatively high levels by November.\n\nOverall, Ozone levels closely follow seasonal temperature trends, peaking in summer (especially January) and reaching their lowest in winter. Autumn and spring serve as transitional periods, with autumn showing a cooling and decreasing trend in ozone, while spring shows warming and increasing ozone levels.\n\n**Plotting Daily Variations Across Each Month**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\np5 <- ggplot(data_wider, aes(y = o3, x = air_tmax)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(se = FALSE) + \n  facet_wrap(~month, ncol = 4) +\n  scale_y_continuous(\"Ozone (ppm)\", breaks = seq(0, max(data_wider$o3, na.rm = TRUE), by = 0.01)) +\n  ylab(\"Max Daily Temp (°C)\") +\n  theme(aspect.ratio = 0.4)\n\np6 <- ggplot(data_wider, aes(y = o3, x = air_tmin)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(se = FALSE) + \n  facet_wrap(~month, ncol = 4) +\n  scale_y_continuous(\"Ozone (ppm)\", breaks = seq(0, max(data_wider$o3, na.rm = TRUE), by = 0.01)) +\n  ylab(\"Max Daily Temp (°C)\") +\n  theme(aspect.ratio = 0.4)\n\np5 \n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\np6\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-16-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- Across all months, there is a generally positive relationship between temperature and ozone levels, with maximum temperature (air_tmax) showing a stronger association with ozone than minimum temperature (air_tmin). As temperatures increase, ozone levels tend to rise, particularly in warmer months with higher maximum temperatures.\n- Monthly variations also reflect these seasonal trends. In summer, especially January, there is a strong, consistent positive relationship between temperature and ozone levels, with warmer months correlating closely with higher ozone levels. In autumn, the positive trend remains but becomes more variable, indicating increased scatter in the temperature-ozone relationship. Winter shows a weaker, less consistent pattern, with minimal correlation between temperature and ozone. By spring, the positive relationship between temperature and ozone begins to stabilize again, especially in November, as temperatures rise toward summer.\n- Some anomalies are evident, such as an unexpected dip in December’s ozone levels at higher minimum temperatures (air_tmin). Additionally, winter months exhibit a weaker pattern, suggesting that factors beyond temperature may influence ozone levels during these periods, a finding also supported by the linear model.\n\n### Permutation and Lineup Test \n\n**Line up for Max Temperature and O3**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(20190709)\nggplot(lineup(null_permute('air_tmax'), data_wider), \n  aes(x=air_tmax, y=o3)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  theme(axis.text=element_blank(),\n        axis.title=element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n#decrypt(\"o0vr 8ZGZ D3 k5fDGD53 M1\")\n```\n:::\n\n\n**Line up for Min Temperature and O3**\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(32632632)\nggplot(lineup(null_permute('air_tmin'), data_wider), \n  aes(x=air_tmin, y=o3)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  theme(axis.text=element_blank(),\n        axis.title=element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n#decrypt(\"o0vr 8ZGZ D3 k5fDGD53 eV\")\n```\n:::\n\n\n- Here, we used visual inference to assess whether a relationship exists between temperature (min & max) and ozone levels. We applied permutation and randomly shuffled the temperature values and plotted them alongside ozone levels across 19 null plots for each line up.  \n- During our visual inference test, participants unanimously identified the real plot in both lineups, demonstrating clear visual relationships between temperature and O3 levels. In the first lineup for maximum temperature and O3, plot 20 was consistently chosen due to its distinct upward trend. Similarly, in the second lineup for minimum temperature and O3, plot 6 stood out as the real plot, with all participants correctly identifying it.\n- These results indicate that both maximum and minimum temperatures have statistically significant and visually distinct relationships with O3 levels. Although maximum temperature may explain more variation in ozone levels, both relationships were equally recognizable, highlighting how both min and max temperatures serve as visually reliable indicators of ozone variation in our analysis.\n\n\n### Conclusion for Relationship 1 \n\nThe analysis provides strong evidence that higher temperatures increase the formation of ground-level ozone (O3). Monthly trends show ozone peaking during warmer months, while scatter plots confirm a positive relationship between temperature and ozone. Linear models reveal that both maximum and minimum temperatures are significant predictors of ozone, with maximum temperature explaining 18.6% and minimum temperature 11.5% of ozone variability. Visual inference tests highlight that the maximum and minimum temperature relationships with O3 are visually identifiable, though maximum temperature provides slightly more insight into variations in ozone levels. Overall, the findings conclude that higher temperatures do indeed drive ground-level ozone formation, particularly during peak daytime temperatures.\n\n\n## Relationship 2\n\n_**Rain and snow can “wash out” particulate matter and water-soluble gases from the air**_\n\nThe next research question is if rain or snow can wash out particulate matter and water-soluble gases from the air. According to the US National Institute of Health [@NIH], water-soluble gases would include o3, so2, and no2. SILO provides daily rainfall (mm) measurements. The following section will explore the relationship between rainfall and pm25, pm10, o3, so2, and no2. \n\n\n**Evaluating Monthly Rainfall Variation**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ndata_wider$month <- as.factor(data_wider$month)\n\nfiltered_rainfall_data_wider <- data_wider %>%\n  filter(rainfall > 0)\n\n\nggplot(filtered_rainfall_data_wider, aes(x = month, y = rainfall)) +\n  geom_boxplot(fill = \"#56B4E9\") +  \n  labs(x = \"Month\", y = \"Rainfall (mm)\") +\n  theme(aspect.ratio = 0.5)\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/2_boxplot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n- This boxplot provides context as to how much rainfall occurs for the two locations in Melbourne for every month. Overall, daily rainfall tends to be around 3mm with April and October having the highest variability. \n- In general, the winter and early spring months tend to have more rainfall than the summer and early autumn months. So, if rain is effective in washing out water-soluble air pollutants, one would expect to see less of those air pollutants during those months.\n\n**Evaluating Average Variation of Pollutants compared to Rainfall**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\noptions(scipen=99)\n\nrain_avg_lines_table <- data_wider %>%\n  group_by(month) %>%\n  summarise(avg_rainfall = mean(rainfall, na.rm = TRUE),\n            avg_so2 = mean(so2, na.rm = TRUE),\n            avg_o3 = mean(o3, na.rm = TRUE),\n            avg_no2 = mean(no2, na.rm = TRUE),\n            avg_pm25 = mean(pm25, na.rm = TRUE),\n            avg_pm10 = mean(pm10, na.rm = TRUE))\n\nrain_avg_lines_table <- rain_avg_lines_table %>%\n  mutate(month = as.numeric(month))\n\n# Create individual plots for each pollutant\no3_plot <- ggplot(rain_avg_lines_table, aes(x = month, y = avg_o3)) +\n  geom_line(color = \"red\", size = 1) +\n   scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg O3 Levels\", x = \"Month\", y = \"Avg o3 (ppm)\") +\n  theme_minimal()\n\nso2_plot <- ggplot(rain_avg_lines_table, aes(x = month, y = avg_so2)) +\n  geom_line(color = \"blue\", size = 1) +\n   scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg SO2 Levels\", x = \"Month\", y = \"Avg so2 (ppm)\") +\n  theme_minimal()\n\nno2_plot <- ggplot(rain_avg_lines_table, aes(x = month, y = avg_no2)) +\n  geom_line(color = \"green\", size = 1) +\n   scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg NO2 Levels\", x = \"Month\", y = \"Avg NO2 (ppm)\") +\n  theme_minimal()\n\npm25_plot <- ggplot(rain_avg_lines_table, aes(x = month, y = avg_pm25)) +\n  geom_line(color = \"purple\", size = 1) +\n   scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg PM2.5 Levels\", x = \"Month\", y = \"Avg PM2.5 (µg/m³)\") +\n  theme_minimal()\n\npm10_plot <- ggplot(rain_avg_lines_table, aes(x = month, y = avg_pm10)) +\n  geom_line(color = \"pink\", size = 1) +\n   scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg PM10 Levels\", x = \"Month\", y = \"Avg pm10 (µg/m³)\") +\n  theme_minimal()\n\nrainfall_plot <-ggplot(rain_avg_lines_table, aes(x = month, y = avg_rainfall)) +\n  geom_line(color = \"lightblue\", size = 1) +\n   scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg Rainfall\", x = \"Month\", y = \"Rainfall (mm)\") +\n       theme_minimal()\n\n# Arrange the plots horizontally using patchwork\ncombined_plot <- o3_plot + so2_plot + no2_plot + pm25_plot + pm10_plot + rainfall_plot\n\n# Display the combined plot\ncombined_plot\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/2_avglines-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- These line graphs show the average pollution and rainfall rates across each month. The average rainfall per month shows fairly stable rainfall with a spike in October and November. In general, if rainfall is to wash out air pollutants, we would expect pm25, pm10, o3, so2, and no2 levels to drop in the early spring and summer months. \n- In these charts, we can see that both no2 and so2 levels decrease from July to December, but it is not entirely clear if there is a relationship. Average o3 levels actually increase from July to December, which is opposite of what one would expect if rainfall were to wash air pollutants. \n- Average pm25 levels decreased from July to October but the steeply increase in November and December. And, average pm10 levels dropped from February to October, then rose in November and December like pm25. Diving deeper into the relationship of rainfall with these pollutants using scatter plots, regressions, and visual inference could provide more clarity.\n\n**Examining Relationships Using Scatterplots**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Scatter plot for rainfall vs o3\nscatter_rainfall_o3 <- ggplot(data_wider, aes(y = o3, x = rainfall)) +\n  geom_point(alpha = 0.5, color = \"red\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkred\") +\n  labs(title = \"Rainfall (mm) vs O3\",\n       y = \"Ozone (ppm)\",\n       x = \"Rainfall (mm)\") +\n  theme_minimal()\n\n# Scatter plot for rainfall  vs. so2\nscatter_rainfall_so2 <- ggplot(data_wider, aes(y = so2, x = rainfall)) +\n  geom_point(alpha = 0.5, color = \"blue\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkblue\") +\n  labs(title = \"Rainfall (mm) vs SO2\",\n       y = \"SO2 (ppm)\",\n       x = \"Rainfall (mm)\") +\n  theme_minimal()\n\n# Scatter plot for rainfall vs no2\nscatter_rainfall_no2 <- ggplot(data_wider, aes(y = no2, x = rainfall)) +\n  geom_point(alpha = 0.5, color = \"green\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkgreen\") +\n  labs(title = \"Rainfall vs NO2\",\n       y = \"NO2 (ppm)\",\n       x = \"Rainfall (mm)\") +\n  theme_minimal()\n\n# Scatter plot for rainfall vs pm25\nscatter_rainfall_pm25 <- ggplot(data_wider, aes(y = pm25, x = rainfall)) +\n  geom_point(alpha = 0.5, color = \"purple\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"#301934\") +\n  labs(title = \"Rainfall vs PM2.5\",\n       y = \"PM2.5 (µg/m³)\",\n       x = \"Rainfall (mm)\") +\n  theme_minimal()\n\n# Scatter plot for rainfall vs pm10\nscatter_rainfall_pm10 <- ggplot(data_wider, aes(y = pm10, x = rainfall)) +\n  geom_point(alpha = 0.5, color = \"pink\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"#e75480\") +\n  labs(title = \"Rainfall vs PM10\",\n       y = \"PM10 (µg/m³)\",\n       x = \"Rainfall (mm)\") +\n  theme_minimal()\n\n# Arrange the two plots side by side for easier comparison\ngrid.arrange(scatter_rainfall_o3, scatter_rainfall_so2, scatter_rainfall_no2, \n             scatter_rainfall_pm25, scatter_rainfall_pm10, ncol = 3)\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/2_scatterplot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- When daily rainfall rates are plotted with each air pollutant, two different stories emerge. There is a slightly positive relationship between rainfall o3. This means that as a location has more rain, there is also an increase in o3. This is contrary to the hypothesis that rain washes out the water-soluble air pollutants.\n- However, there is a slightly negative relationship between rainfall and so2, no2, pm2.5, and pm10. This means that as a location has more rain, there is a decrease in sulfur dioxide, nitrogen dioxide, pm2.5, and pm10. This is aligned with the hypothesis that rain can wash out particulate matter and water-soluble air pollutants.\n- So, based on the scatter points and above plots, there is some evidence that rain can wash out so2, no2, pm2.5, and pm10 but not o3. Further testing using linear modeling and permutation can provide a more informed answer. \n\n### Linear Models\n \n 1. **Linear Modeling of Rainfall with O3**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#rainfall affect on o3 - insignificant\nlm_rainfall_o3 <- lm(o3 ~ rainfall, data = data_wider)\nsummary(lm_rainfall_o3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = o3 ~ rainfall, data = data_wider)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.014186 -0.003797 -0.000546  0.003454  0.024454 \n\nCoefficients:\n             Estimate Std. Error t value\n(Intercept) 0.0145461  0.0002455   59.25\nrainfall    0.0000660  0.0000482    1.37\n                       Pr(>|t|)    \n(Intercept) <0.0000000000000002 ***\nrainfall                   0.17    \n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0061 on 719 degrees of freedom\nMultiple R-squared:  0.0026,\tAdjusted R-squared:  0.00121 \nF-statistic: 1.87 on 1 and 719 DF,  p-value: 0.172\n```\n\n\n:::\n:::\n\n\n- With a p-value greater than .05, there is not a statistically significant relationship between rainfall and o3. Rainfall does not have a meaningful effect on the amount of o3 in the air.\n\n2. **Linear Modeling of Rainfall with SO2**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#rainfall affect on so2 - significant\nlm_rainfall_so2 <- lm(so2 ~ rainfall, data = data_wider)\nsummary(lm_rainfall_so2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = so2 ~ rainfall, data = data_wider)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.0004482 -0.0002500 -0.0000543  0.0001934  0.0024526 \n\nCoefficients:\n               Estimate  Std. Error t value\n(Intercept)  0.00044816  0.00001308   34.27\nrainfall    -0.00000764  0.00000257   -2.97\n                       Pr(>|t|)    \n(Intercept) <0.0000000000000002 ***\nrainfall                  0.003 ** \n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.00032 on 719 degrees of freedom\nMultiple R-squared:  0.0122,\tAdjusted R-squared:  0.0108 \nF-statistic: 8.84 on 1 and 719 DF,  p-value: 0.00304\n```\n\n\n:::\n:::\n\n\n- With a p-value lower than .01, there is a statistically significant relationship between rainfall and so2. When rainfall is zero, the predicted so2 levels are 0.000448 ppm. For every additional mm of rainfall, so2 levels decrease by 0.00000764 ppm. \n- This means that higher rainfall is associated with lower levels of so2. The R² value is .0122, suggesting that only 12% of the variability of so2 is explained by rainfall. This means that there are other factors that contribute to the levels of so2 in the air besides rainfall. \n\n3. **Linear Modeling of Rainfall with NO2**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#rainfall affect on no2 - significant\nlm_rainfall_no2 <- lm(no2 ~ rainfall, data = data_wider)\n\nsummary(lm_rainfall_no2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = no2 ~ rainfall, data = data_wider)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.00793 -0.00373 -0.00113  0.00281  0.01757 \n\nCoefficients:\n              Estimate Std. Error t value\n(Intercept)  0.0094339  0.0001927   48.95\nrainfall    -0.0001084  0.0000377   -2.87\n                       Pr(>|t|)    \n(Intercept) <0.0000000000000002 ***\nrainfall                 0.0042 ** \n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0047 on 708 degrees of freedom\n  (11 observations deleted due to missingness)\nMultiple R-squared:  0.0115,\tAdjusted R-squared:  0.0101 \nF-statistic: 8.25 on 1 and 708 DF,  p-value: 0.00419\n```\n\n\n:::\n:::\n\n\n- With a p-value lower than .01, there is a statistically significant relationship between rainfall and no2. When rainfall is zero, the predicted no2 levels are 0.00943 ppm. For every additional mm of rainfall, no2 levels decreases by 0.000108 ppm. \n- This means that higher rainfall is associated with lower levels of no2. The R² value is .0115, suggesting that only 1% of the variability in no2 is explained by rainfall. This means that there are many other factors that contribute to the levels of so2 in the air besides rainfall.\n\n4. **Linear Modeling of Rainfall with PM25**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#rainfall affect on pm25\nlm_rainfall_pm25 <- lm(pm25 ~ rainfall, data = data_wider)\n\nsummary(lm_rainfall_pm25)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = pm25 ~ rainfall, data = data_wider)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -6.50  -2.38  -0.86   1.34  32.44 \n\nCoefficients:\n            Estimate Std. Error t value\n(Intercept)   6.5566     0.1518   43.19\nrainfall     -0.1319     0.0317   -4.16\n                        Pr(>|t|)    \n(Intercept) < 0.0000000000000002 ***\nrainfall                0.000036 ***\n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.7 on 696 degrees of freedom\n  (23 observations deleted due to missingness)\nMultiple R-squared:  0.0243,\tAdjusted R-squared:  0.0229 \nF-statistic: 17.3 on 1 and 696 DF,  p-value: 0.0000358\n```\n\n\n:::\n:::\n\n\n- With a p-value lower than .01, there is a statistically significant relationship between rainfall and PM2.5. When rainfall is zero, the predicted PM2.5 levels are 6.5566 µg/m³. For every additional mm of rainfall, PM2.5 levels decrease by 0.1319 µg/m³. \n- This means that higher rainfall is associated with lower levels of PM2.5. The R² value is 0.0243, suggesting that only 2.43% of the variability of PM2.5 is explained by rainfall. This means that there are other factors that contribute to the levels of PM2.5 in the air besides rainfall.\n\n5. **Linear Modeling of Rainfall with PM10**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#rainfall affect on pm10\nlm_rainfall_pm10 <- lm(pm10 ~ rainfall, data = data_wider)\n\nsummary(lm_rainfall_pm10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = pm10 ~ rainfall, data = data_wider)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-12.64  -5.26  -0.87   3.32  49.13 \n\nCoefficients:\n            Estimate Std. Error t value\n(Intercept)   16.872      0.294   57.39\nrainfall      -0.326      0.057   -5.71\n                        Pr(>|t|)    \n(Intercept) < 0.0000000000000002 ***\nrainfall             0.000000017 ***\n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.2 on 700 degrees of freedom\n  (19 observations deleted due to missingness)\nMultiple R-squared:  0.0445,\tAdjusted R-squared:  0.0431 \nF-statistic: 32.6 on 1 and 700 DF,  p-value: 0.0000000169\n```\n\n\n:::\n:::\n\n\n- With a p-value lower than .01, there is a statistically significant relationship between rainfall and PM10. When rainfall is zero, the predicted PM10 levels are 16.872 µg/m³. For every additional mm of rainfall, PM10 levels decrease by 0.326 µg/m³. \n- This means that higher rainfall is associated with lower levels of PM10. The R² value is 0.0445, suggesting that only 4.45% of the variability of PM10 is explained by rainfall. This means that there are other factors that contribute to the levels of PM10 in the air besides rainfall.\n\n\nOf the five air pollutants, linear modelling provides the most amount of evidence that rainfall washes out so2. This is because there is a statistically significant relationship between rainfall and so2 and rainfall explains a higher proportion of the variability of so2 compared to no2, pm25, and pm10. There is also a statistically significant relationship with rainfall and no2, pm25, and pm10, but the low R² values show that 1-4% of the variability is explained by rainfall. So, it is less clear if rainfall actually contributes to lower no2, pm25, and pm10 levels or if it is simply just a correlation. \n\n### Permutation and Lineup Test \n\n**Line up for Rainfall and O3**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(10)\n# Rainfall and O3\nggplot(lineup(null_permute('rainfall'), data_wider), \n       aes(x = rainfall, y = o3)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  #labs(title = \"Rainfall vs O3\") +\n  theme(axis.text = element_blank(),\n        axis.title = element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/2_lineup_o3-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n#decrypt(\"4nZe kSDS Ec whQEDEhc o2\")\n```\n:::\n\n\n**Lineup for Rainfall and SO2**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(10)\n# Rainfall and SO2\nggplot(lineup(null_permute('rainfall'), data_wider), \n       aes(x = rainfall, y = so2)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  #labs(title = \"Rainfall vs SO2\") +\n  theme(axis.text = element_blank(),\n        axis.title = element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/2_lineup_so2-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n#decrypt(\"4nZe kSDS Ec whQEDEhc VV\")\n```\n:::\n\n\n**Lineup for Rainfall and NO2**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(10)\n# Rainfall and NO2\nggplot(lineup(null_permute('rainfall'), data_wider), \n       aes(x = rainfall, y = no2)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  #labs(title = \"Rainfall vs NO2\") +\n  theme(axis.text = element_blank(),\n        axis.title = element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/2_lineup_no2-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n#decrypt(\"4nZe kSDS Ec whQEDEhc o0\")\n```\n:::\n\n\n**Lineup for Rainfall and PM2.5**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(10)\n# Rainfall and PM25\nggplot(lineup(null_permute('rainfall'), data_wider), \n       aes(x = rainfall, y = pm25)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  #labs(title = \"Rainfall vs PM2.5\") +\n  theme(axis.text = element_blank(),\n        axis.title = element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/2_lineup_pm25-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n#decrypt(\"4nZe kSDS Ec whQEDEhc 0N\")\n```\n:::\n\n\n**Lineup for Rainfall and PM10**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(10)\n# Rainfall and PM10\nggplot(lineup(null_permute('rainfall'), data_wider), \n       aes(x = rainfall, y = pm10)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  #labs(title = \"Rainfall vs PM10\") +\n  theme(axis.text = element_blank(),\n        axis.title = element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/2_lineup_pm10-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n#decrypt(\"4nZe kSDS Ec whQEDEhc o0\")\n```\n:::\n\n\n- Finally, visual inference can be used to test if there is a relationship between rainfall and air pollution levels. This is done by permuting or shuffling the rainfall values and then plotting them with the o3, so2, no2, pm25, and pm10 levels 19 times. \n- If the original scatter plot is identifiable next to the 19 null plots, then there is evidence that there is a relationship between the rainfall and the air pollutants.\n- When doing this test with our research team and other peers, it was difficult to differentiate the plots and correctly identify the real plot. \n- So, although the linear modeling suggests that that there are statistically significant relationships between rainfall and no2, so2, pm10, and pm25, these relationships are not as evident in the permutation and nullplot tests. \n\n### Conclusion for Relationship 2\n\nThere is some evidence that rainfall might wash out so2, no2, pm10, and pm25, but not o3. When average rainfall and air pollution levels are plotted over time, we can see a general trend that as rainfall increases that so2, no2, pm25, and pm10 decrease while o3 increases. This is further supported when rainfall and air pollutants are plotted in a scatter plot. Linear modeling shows a statistically significant negative relationship between rainfall and so2, no2, pm25, and pm10. So2 has 12% of its variability explained by rainfall while no2, pm25, and pm10 have 1-4% of their variability explained by rainfall. Finally, it was difficult to correctly identify the correct plot when doing visual inference through the use of permutation and nullplots. This suggests that although there is some evidence of relationships in the linear modeling, it may not be that strong. It is clear that there are other factors that affect the levels of air pollutants in the air besides rainfall. \n\n## Relationship 3\n\n_**High-pressure systems often lead to stagnant air, trapping pollutants**_\n\nThis research question examines whether high-pressure systems, which create stagnant atmospheric conditions, contribute to the buildup of pollutants near the ground. This analysis focuses on various pollutants, including particulate matter (PM2.5 and PM10), ozone (O3), sulfur dioxide (SO2), nitrogen dioxide (NO2), and carbon monoxide (CO), assessing their relationship with mean sea level pressure (MSLP). The following section explores how high-pressure conditions may influence pollutant concentrations, providing insights into the extent to which these atmospheric conditions impact air quality.\n\n**Evaluating Monthly Mean Sea Level Pressure (MSLP) Variation**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ndata_wider$month <- as.factor(data_wider$month)\n\nggplot(data_wider, aes(x=month, y=mslp)) +\n  geom_boxplot(fill= \"#56B4E9\") +\n  labs(x = \"Month\", y = \"Mean Sea Level Pressure\") +\n  theme(aspect.ratio=0.5)\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- The box plot reveals seasonal patterns in mean sea level pressure (MSLP) across the year. July has the highest median MSLP, indicating strong high-pressure conditions in mid-winter that could lead to stagnant air and the trapping of pollutants. \n- May and August show greater variability, with wider ranges and outliers, reflecting fluctuations during transitional months. This variability may result in alternating conditions of pollutant trapping and dispersion.\n- In contrast, summer months, especially January, have lower and more stable MSLP values, suggesting consistent low-pressure conditions that likely facilitate better air circulation and pollutant dispersion. \n- Overall, this seasonal pattern implies that winter’s higher and more stable MSLP may contribute to pollutant accumulation, while summer’s lower MSLP aids in clearing the air. \n\n\n**Evaluating Average Variation of Pollutants compared to MSLP**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\noptions(scipen=99)\n\nmslp_avg_lines_table <- data_wider %>%\n  group_by(month) %>%\n  summarise(avg_mslp = mean(mslp, na.rm = TRUE),\n            avg_so2 = mean(so2, na.rm = TRUE),\n            avg_o3 = mean(o3, na.rm = TRUE),\n            avg_no2 = mean(no2, na.rm = TRUE),\n            avg_pm25 = mean(pm25, na.rm = TRUE),\n            avg_pm10 = mean(pm10, na.rm = TRUE),\n            avg_co = mean(co, na.rm = TRUE))\n\nmslp_avg_lines_table <- mslp_avg_lines_table %>%\n  mutate(month = as.numeric(month))\n\n# Create individual plots for each pollutant\no3 <- ggplot(mslp_avg_lines_table, aes(x = month, y = avg_o3)) +\n  geom_line(color = \"red\", size = 1) +\n   scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg O3 Levels\", x = \"Month\", y = \"Avg o3 (ppm)\") +\n  theme_minimal()\n\nso2 <- ggplot(mslp_avg_lines_table, aes(x = month, y = avg_so2)) +\n  geom_line(color = \"blue\", size = 1) +\n   scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg SO2 Levels\", x = \"Month\", y = \"Avg so2 (ppm)\") +\n  theme_minimal()\n\nno2 <- ggplot(mslp_avg_lines_table, aes(x = month, y = avg_no2)) +\n  geom_line(color = \"green\", size = 1) +\n   scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg NO2 Levels\", x = \"Month\", y = \"Avg NO2 (ppm)\") +\n  theme_minimal()\n\npm25 <- ggplot(mslp_avg_lines_table, aes(x = month, y = avg_pm25)) +\n  geom_line(color = \"purple\", size = 1) +\n   scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg PM2.5 Levels\", x = \"Month\", y = \"Avg PM2.5 (µg/m³)\") +\n  theme_minimal()\n\npm10  <- ggplot(mslp_avg_lines_table, aes(x = month, y = avg_pm10)) +\n  geom_line(color = \"pink\", size = 1) +\n   scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg PM10 Levels\", x = \"Month\", y = \"Avg pm10 (µg/m³)\") +\n  theme_minimal()\n\nco  <- ggplot(mslp_avg_lines_table, aes(x = month, y = avg_co)) +\n  geom_line(color = \"orange\", size = 1) +\n   scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg CO Levels\", x = \"Month\", y = \"Avg CO (ppm)\") +\n  theme_minimal()\n\nmslp <-ggplot(mslp_avg_lines_table, aes(x = month, y = avg_mslp)) +\n  geom_line(color = \"lightblue\", size = 1) +\n   scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg MSLP\", x = \"Month\", y = \"MSLP\") +\n       theme_minimal()\n\n\n\ngrid.arrange(o3, so2, no2, pm25, pm10, co, mslp, ncol = 3)\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-20-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n- These line graphs illustrate the average monthly levels of various air pollutants (O3, SO2, NO2, PM2.5, PM10, and CO) alongside mean sea level pressure (MSLP). MSLP follows a seasonal pattern, peaking in winter (May to August) and dipping in summer (December to February). If high MSLP is associated with air stagnation, we might expect pollutant levels to increase during winter and decrease in summer.\n- In these charts, NO2 and CO closely follow MSLP trends, with higher levels in winter and lower levels in summer. O3, however, shows an inverse trend, peaking in summer and declining in winter, likely due to the influence of sunlight in ozone formation. \n- PM2.5 exhibits fluctuating peaks throughout autumn and winter, indicating seasonal variability that may be influenced by both MSLP and other factors like seasonal emissions or heating. \n- In contrast, PM10 does not display a consistent winter increase, with lower levels during high-pressure months, suggesting a slight inverse relationship with MSLP, especially in summer. \n- SO2 levels generally decline through the year, with some variability. Further analysis, including scatter plots and regression models, could help clarify the effects of seasonal pressure changes on these pollutants.\n\n\n**Examining Relationships Using Scatterplots**\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Scatter plot for MSLP vs o3\nscatter_mslp_o3 <- ggplot(data_wider, aes(y = o3, x = mslp)) +\n  geom_point(alpha = 0.5, color = \"red\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkred\") +\n  labs(title = \"MSLP vs O3\",\n       y = \"Ozone (ppm)\",\n       x = \"MSLP\") +\n  theme_minimal()\n\n# Scatter plot for MSLP  vs. so2\nscatter_mslp_so2 <- ggplot(data_wider, aes(y = so2, x = mslp)) +\n  geom_point(alpha = 0.5, color = \"blue\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkblue\") +\n  labs(title = \"MSLP vs SO2\",\n       y = \"SO2 (ppm)\",\n       x = \"MSLP\") +\n  theme_minimal()\n\n# Scatter plot for MSLP vs no2\nscatter_mslp_no2 <- ggplot(data_wider, aes(y = no2, x = mslp)) +\n  geom_point(alpha = 0.5, color = \"green\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkgreen\") +\n  labs(title = \"MSLP vs NO2\",\n       y = \"NO2 (ppm)\",\n       x = \"MSLP\") +\n  theme_minimal()\n\n# Scatter plot for MSLP vs pm25\nscatter_mslp_pm25 <- ggplot(data_wider, aes(y = pm25, x = mslp)) +\n  geom_point(alpha = 0.5, color = \"purple\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"#301934\") +\n  labs(title = \"MSLP vs PM2.5\",\n       y = \"PM2.5 (µg/m³)\",\n       x = \"MSLP\") +\n  theme_minimal()\n\n# Scatter plot for MSLP vs pm10\nscatter_mslp_pm10 <- ggplot(data_wider, aes(y = pm10, x = mslp)) +\n  geom_point(alpha = 0.5, color = \"pink\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"#e75480\") +\n  labs(title = \"MSLP vs PM10\",\n       y = \"PM10 (µg/m³)\",\n       x = \"MSLP\") +\n  theme_minimal()\n\n# Scatter plot for MSLP vs CO\nscatter_mslp_co <- ggplot(data_wider, aes(y = co, x = mslp)) +\n  geom_point(alpha = 0.5, color = \"orange\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"black\") +\n  labs(title = \"MSLP vs CO\",\n       y = \"CO (ppm)\",\n       x = \"MSLP\") +\n  theme_minimal()\n\n\ngrid.arrange(scatter_mslp_o3, scatter_mslp_so2, scatter_mslp_no2, \n             scatter_mslp_pm25, scatter_mslp_pm10, scatter_mslp_co, ncol = 3)\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- The scatter plots display the relationships between mean sea level pressure (MSLP) and various air pollutants, offering insights into how high-pressure systems may influence air quality by either trapping pollutants or allowing for dispersion. \n- O3 shows a moderately negative relationship with MSLP, with lower ozone levels during high-pressure conditions, likely due to reduced sunlight and limited dispersion under stagnant air. In contrast NO2 and CO both have a positive relationship with MSLP, indicating that higher MSLP can trap these pollutants near ground level, preventing their dispersion and leading to accumulation under stable, high-pressure conditions.\n- Both PM2.5 and PM10 exhibit a weaker but still positive relationship with MSLP, suggesting that high-pressure conditions may contribute to their buildup, though the relationship is weaker than for NO2 and CO. SO2 has minimal correlation with MSLP, indicating its levels are more influenced by localized sources rather than atmospheric pressure patterns.\n- Overall, these findings support the that high MSLP conditions, often associated with stagnant air, can lead to the accumulation of pollutants like NO2, CO, PM2.5, and PM10.\n\n### Linear Models\n\n**Linear Modeling of Mean Sea Level Pressure with O3**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#mslp affect on o3 \nlm_mslp_o3 <- lm(o3 ~ mslp, data = data_wider)\nsummary(lm_mslp_o3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = o3 ~ mslp, data = data_wider)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.014428 -0.003827 -0.000261  0.003246  0.024623 \n\nCoefficients:\n              Estimate Std. Error t value\n(Intercept)  0.2985004  0.0265844    11.2\nmslp        -0.0002790  0.0000261   -10.7\n                       Pr(>|t|)    \n(Intercept) <0.0000000000000002 ***\nmslp        <0.0000000000000002 ***\n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0057 on 719 degrees of freedom\nMultiple R-squared:  0.137,\tAdjusted R-squared:  0.136 \nF-statistic:  114 on 1 and 719 DF,  p-value: <0.0000000000000002\n```\n\n\n:::\n:::\n\n- With a p-value well below 0.01, there is a statistically significant inverse relationship between mean sea level pressure (MSLP) and ozone levels. For each unit increase in MSLP, ozone levels decrease by 0.000279 ppm, suggesting that higher pressure is associated with lower ozone levels. \n- This supports the idea that high-pressure systems, which reduce air dispersal, tend to trap pollutants but do not directly promote ozone formation, as it is more influenced by sunlight and temperature. \n- The R-squared value of 0.137 indicates that MSLP accounts for about 13.7% of the variation in ozone levels, with other factors also contributing.\n\n**Linear Modeling of Mean Sea Level Pressure with SO2**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#mslp affect on SO2 \nlm_mslp_so2 <- lm(so2 ~ mslp, data = data_wider)\nsummary(lm_mslp_so2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = so2 ~ mslp, data = data_wider)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.0004920 -0.0002474 -0.0000573  0.0001889  0.0024102 \n\nCoefficients:\n               Estimate  Std. Error t value Pr(>|t|)   \n(Intercept) -0.00435962  0.00152083   -2.87   0.0043 **\nmslp         0.00000471  0.00000149    3.15   0.0017 **\n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.00032 on 719 degrees of freedom\nMultiple R-squared:  0.0136,\tAdjusted R-squared:  0.0123 \nF-statistic: 9.93 on 1 and 719 DF,  p-value: 0.00169\n```\n\n\n:::\n:::\n\n\n- With a p-value below 0.01, there is a statistically significant positive relationship between mean sea level pressure (MSLP) and SO2 levels. For each unit increase in MSLP, SO2 levels increase by 0.00000471 ppm, suggesting that higher pressure is associated with slightly elevated SO2 levels. \n- This supports the idea that high-pressure systems may trap pollutants, including SO2, due to reduced air dispersal. However, the R-squared value is only 0.0136, indicating that MSLP explains just 1.36% of the variability in SO2 levels, so other factors also play a significant role in influencing SO2 concentrations.\n\n\n**Linear Modeling of Mean Sea Level Pressure with NO2**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#mslp affect on NO2 \nlm_mslp_no2 <- lm(no2 ~ mslp, data = data_wider)\nsummary(lm_mslp_no2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = no2 ~ mslp, data = data_wider)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.008455 -0.003400 -0.000823  0.002809  0.015231 \n\nCoefficients:\n              Estimate Std. Error t value\n(Intercept) -0.2282715  0.0206867   -11.0\nmslp         0.0002334  0.0000203    11.5\n                       Pr(>|t|)    \n(Intercept) <0.0000000000000002 ***\nmslp        <0.0000000000000002 ***\n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0044 on 708 degrees of freedom\n  (11 observations deleted due to missingness)\nMultiple R-squared:  0.157,\tAdjusted R-squared:  0.156 \nF-statistic:  132 on 1 and 708 DF,  p-value: <0.0000000000000002\n```\n\n\n:::\n:::\n\n\n- With a p-value much lower than 0.01, there is a statistically significant positive relationship between mean sea level pressure (MSLP) and NO2 levels. For each unit increase in MSLP, NO2 levels increase by 0.0002334 ppm, indicating that higher pressure is associated with slightly elevated NO2 levels. \n- This finding aligns with the notion that high-pressure systems can trap pollutants due to reduced air dispersal, potentially increasing NO2 concentrations. \n- The R-squared value of 0.157 indicates that MSLP explains about 15.7% of the variability in NO2 levels, suggesting that while MSLP has a noticeable influence, other factors also contribute significantly to NO2 concentrations.\n\n\n**Linear Modeling of Mean Sea Level Pressure with PM2.5**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#mslp affect on pm25 \nlm_mslp_pm25 <- lm(pm25 ~ mslp, data = data_wider)\nsummary(lm_mslp_pm25)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = pm25 ~ mslp, data = data_wider)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -6.15  -2.20  -0.74   1.40  33.13 \n\nCoefficients:\n             Estimate Std. Error t value\n(Intercept) -150.7612    16.5793   -9.09\nmslp           0.1544     0.0163    9.47\n                       Pr(>|t|)    \n(Intercept) <0.0000000000000002 ***\nmslp        <0.0000000000000002 ***\n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.5 on 696 degrees of freedom\n  (23 observations deleted due to missingness)\nMultiple R-squared:  0.114,\tAdjusted R-squared:  0.113 \nF-statistic: 89.8 on 1 and 696 DF,  p-value: <0.0000000000000002\n```\n\n\n:::\n:::\n\n\n- With a p-value much lower than 0.01, there is a statistically significant positive relationship between mean sea level pressure (MSLP) and PM2.5 levels. For each unit increase in MSLP, PM2.5 levels increase by 0.1544 µg/m³, suggesting that higher pressure is associated with higher PM2.5 concentrations. \n- This aligns with the idea that high-pressure systems can trap particulate matter due to reduced air movement, leading to an accumulation of pollutants like PM2.5. \n- The R-squared value of 0.114 indicates that about 11.4% of the variability in PM2.5 levels is explained by MSLP, implying that while MSLP has an influence, other factors —such as traffic emissions, industrial activities, and seasonal weather variations—also play important roles in shaping PM2.5 concentrations.\n\n\n**Linear Modeling of Mean Sea Level Pressure with PM10**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#mslp affect on pm10\nlm_mslp_pm10 <- lm(pm10 ~ mslp, data = data_wider)\nsummary(lm_mslp_pm10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = pm10 ~ mslp, data = data_wider)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-15.77  -5.11  -1.07   3.39  50.33 \n\nCoefficients:\n             Estimate Std. Error t value      Pr(>|t|)    \n(Intercept) -197.0526    33.8464   -5.82 0.00000000886 ***\nmslp           0.2097     0.0333    6.30 0.00000000052 ***\n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.2 on 700 degrees of freedom\n  (19 observations deleted due to missingness)\nMultiple R-squared:  0.0537,\tAdjusted R-squared:  0.0523 \nF-statistic: 39.7 on 1 and 700 DF,  p-value: 0.00000000052\n```\n\n\n:::\n:::\n\n\n- With a p-value significantly below 0.01, this model establishes a statistically significant positive relationship between mean sea level pressure (MSLP) and PM10 levels. For each unit increase in MSLP, PM10 levels rise by 0.2097 µg/m³, supporting the concept that high-pressure systems can trap pollutants like PM10 by limiting air dispersal. \n- However, with an R-squared value of 0.0537, MSLP explains only about 5.4% of the variability in PM10, indicating that other factors—such as local emissions from traffic and industry, seasonal weather patterns, and temperature—likely contribute significantly to PM10 concentrations.\n\n\n**Linear Modeling of Mean Sea Level Pressure with CO**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#mslp affect on CO\nlm_mslp_co <- lm(co ~ mslp, data = data_wider)\nsummary(lm_mslp_co)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = co ~ mslp, data = data_wider)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-0.2094 -0.0649 -0.0153  0.0403  0.5774 \n\nCoefficients:\n             Estimate Std. Error t value\n(Intercept) -5.082186   0.457175   -11.1\nmslp         0.005178   0.000449    11.5\n                       Pr(>|t|)    \n(Intercept) <0.0000000000000002 ***\nmslp        <0.0000000000000002 ***\n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.097 on 707 degrees of freedom\n  (12 observations deleted due to missingness)\nMultiple R-squared:  0.158,\tAdjusted R-squared:  0.157 \nF-statistic:  133 on 1 and 707 DF,  p-value: <0.0000000000000002\n```\n\n\n:::\n:::\n\n\n- The linear model reveals a statistically significant positive relationship between mean sea level pressure (MSLP) and CO levels, as indicated by a very low p-value (< 0.01). For every unit increase in MSLP, CO levels rise by 0.005178 ppm, suggesting that higher pressures are associated with elevated CO concentrations. This supports that high-pressure systems may trap pollutants like CO, limiting their dispersion. \n- However, with an R-squared value of 0.158, MSLP explains only 15.8% of the variability. Other factors likely contribute to CO levels, primarily vehicle emissions and industrial activities, which are significant sources of carbon monoxide in the atmosphere.\n\n\nOverall, MSLP has the strongest effect on CO and NO2 levels, explaining about 15-16% of their variability and suggesting that high-pressure systems can trap these pollutants. While MSLP also significantly influences PM2.5, PM10, and SO2, the lower R-squared values (5-11%) imply that other factors more heavily impact these pollutants.\n\n### Permutation and Lineup Test \n\n**Line up for Mean Sea Level Pressure and O3**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(362362)\nggplot(lineup(null_permute('mslp'), data_wider), \n  aes(x=mslp, y=o3)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  theme(axis.text=element_blank(),\n        axis.title=element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-28-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**Line up for Mean Sea Level Pressure and SO2** \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(123456)\nggplot(lineup(null_permute('mslp'), data_wider), \n  aes(x=mslp, y=so2)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  theme(axis.text=element_blank(),\n        axis.title=element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**Line up for Mean Sea Level Pressure and NO2** \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(272923)\nggplot(lineup(null_permute('mslp'), data_wider), \n  aes(x=mslp, y=no2)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  theme(axis.text=element_blank(),\n        axis.title=element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**Line up for Mean Sea Level Pressure and PM25** \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(754638)\nggplot(lineup(null_permute('mslp'), data_wider), \n  aes(x=mslp, y=pm25)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  theme(axis.text=element_blank(),\n        axis.title=element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**Line up for Mean Sea Level Pressure and PM10** \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(659812)\nggplot(lineup(null_permute('mslp'), data_wider), \n  aes(x=mslp, y=pm10)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  theme(axis.text=element_blank(),\n        axis.title=element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-32-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**Line up for Mean Sea Level Pressure and CO** \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(129132)\nggplot(lineup(null_permute('mslp'), data_wider), \n  aes(x=mslp, y=co)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  theme(axis.text=element_blank(),\n        axis.title=element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/unnamed-chunk-33-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- Visual inference through permutation-based lineup tests was useful in assessing the relationship between Mean Sea Level Pressure (MSLP) and various pollutants. By randomly shuffling MSLP values and plotting them against O3, SO2, NO2, PM2.5, PM10, and CO levels 19 times, we aimed to see if the original relationship stood out among the randomized plots.\n- When conducting this test with peers and our research team, participants consistently identified the real plot for O3, NO2, and CO, indicating that the relationship between MSLP and these pollutants was visually distinct. \n- In contrast, SO2 and PM10 proved challenging, with most participants unable to confidently identify the original plot. For PM2.5, responses were mixed, with some participants able to discern the correct plot while others were not.\n- These findings largely align with the linear models, where pollutants with a relatively higher R-squared value (such as O3, NO2 and CO) had more distinct plots in the lineup tests, supporting the idea that MSLP influences these pollutants more strongly. This suggests that while MSLP affects multiple pollutants, it has the most substantial impact on NO2 and CO in terms of trapping pollutants under high-pressure conditions.\n\n### Conclusion for Relationship 3\n\nThe analysis supports that high-pressure systems, indicated by mean sea level pressure (MSLP), contribute to the accumulation of pollutants like NO2, CO, and, to a lesser extent, PM2.5 and PM10, by limiting air dispersal. Conversely, ozone (O3) shows an inverse relationship with MSLP, likely due to reduced sunlight and mixing under stagnant conditions. Linear modeling reinforces these findings, with NO2 and CO showing the strongest correlations, as indicated by higher R-squared values, suggesting a notable impact of MSLP on their concentrations. Visual inference tests further validated these relationships, as participants consistently identified the real plots for NO2 and CO, aligning with their clear response to MSLP. In conclusion, the findings affirm that high-pressure systems contribute to air stagnation, trapping pollutants and particularly increasing concentrations of NO₂ and CO compared to other pollutants.\n\n## Relationship 4\n\n_**Sunlight drives photochemical reactions that form secondary pollutants like ozone**_\n\nThe last research question is if sunlight drives photochemical reactions that form secondary pollutants like ozone. This analysis will focus on the secondary pollutants of o3 and no2. SILO provides daily solar radiation daily values that are measured in MJ/m2. The following section will explore the relationship between sunlight with o3 and no2. \n\n\n**Evaluating Monthly Radiation Variation**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ndata_wider$month <- as.factor(data_wider$month)\n\n# Violin plot for each month\nggplot(data_wider, aes(x=month, y=radiation)) +\n  geom_violin(draw_quantiles=c(0.25, 0.5, 0.75), fill= \"#56B4E9\") +\n  labs(x = \"Month\", y = \"Solar Radiation (MJ/m2)\") +\n  theme(aspect.ratio=0.5)\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/4_violin-1.png){fig-align='center' width=100%}\n:::\n:::\n\n- The violin plot visualises how sunlight is highest during the summer months and lowest during the winter months in Melbourne. So, if it is true that sunlight drives photochemical reactions that produce secondary pollutants, we would  expect to see higher o3 and no2 values during the summer months. \n\n**Evaluating Average Variation of Pollutants compared to Radiation**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Summarize the data by month to get the average solar radiation, o3 and no2\nradiation_avg_lines_table <- data_wider %>%\n  group_by(month) %>%\n  summarise(avg_radiation = mean(radiation, na.rm = TRUE),\n            avg_o3 = mean(o3, na.rm = TRUE),\n            avg_no2 = mean(no2, na.rm = TRUE))\n\nradiation_avg_lines_table <- radiation_avg_lines_table %>%\n  mutate(month = as.numeric(month))\n\n# Create individual plots for each pollutant\no3_plot_radiation <- ggplot(radiation_avg_lines_table, aes(x = month, y = avg_o3)) +\n  geom_line(color = \"red\", size = 1) +\n  labs(title = \"Avg O3 Levels\", x = \"Month\", y = \"Avg O3 (ppm)\") +\n  scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  theme_minimal()\n\n\n\nno2_plot_radiation <- ggplot(radiation_avg_lines_table, aes(x = month, y = avg_no2)) +\n  geom_line(color = \"green\", size = 1) +\n  scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n  labs(title = \"Avg NO2 Levels\", x = \"Month\", y = \"Avg NO2 (ppm)\") +\n  theme_minimal()\n\nradiation_plot <-ggplot(radiation_avg_lines_table, aes(x = month, y = avg_radiation)) +\n  geom_line(color = \"lightblue\", size = 1) +\n  labs(title = \"Avg Radiation\", x = \"Month\", y = \"Radiation (mm)\") +\n  scale_x_continuous(breaks = 1:12, labels = c(\"J\", \"F\", \"M\", \"A\", \"M\", \"J\", \n                                               \"J\", \"A\", \"S\", \"O\", \"N\", \"D\")) +\n       theme_minimal()\n\n# Arrange the plots horizontally using patchwork\ncombined_plot_radiation <- o3_plot_radiation + no2_plot_radiation + radiation_plot\n\n# Display the combined plot\ncombined_plot_radiation\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/4_avglines-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- The line graphs show the average o3, no2, and solar radiation levels across the months of 2022. Consistent with the violin plot, the radiation line graph shows how sunlight is stronger in the summer months and dimmer in the winter months. \n- The o3 line graph shows that ozone levels behave similarly, having higher o3 levels in the summer and weaker levels in the winter. \n- Conversely, no2 has weaker levels in the summer and higher levels in the winter. So, it is possible that sunlight produces more o3. \n- More testing with linear modelling and visual inferencing can be done get a more informed answer. \n\n**Examining Relationships Using Scatterplots**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Scatter plot for radiation vs o3\nscatter_radiation_o3 <- ggplot(data_wider, aes(y = o3, x = radiation)) +\n  geom_point(alpha = 0.5, color = \"red\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkred\") +\n  labs(title = \"Radiation (mm) vs O3\",\n       y = \"Ozone (ppm)\",\n       x = \"Radiation\") +\n  theme_minimal()\n\n# Scatter plot for radiation vs no2\nscatter_radiation_no2 <- ggplot(data_wider, aes(y = no2, x = radiation)) +\n  geom_point(alpha = 0.5, color = \"green\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkgreen\") +\n  labs(title = \"Radiation vs NO2\",\n       y = \"Nitrogen Dioxide (ppm)\",\n       x = \"Radiation\") +\n  theme_minimal()\n\n# Arrange the two plots side by side for easier comparison\ngrid.arrange(scatter_radiation_o3, scatter_radiation_no2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/4_scatterplot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe scatter plots further reveal the relationship that sunlight has with o3 and no2. As solar radiation increases, o3 increases and no2 decreases. It is possible that sunlight causes secondary pollutants like ozone to be produced while it is also causes pollutants like no2 to be broken down.\n\n### Linear Models \n\n1. **Linear Modeling of Sunlight with O3**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#radiation affect on o3\nlm_radiation_o3 <- lm(o3 ~ radiation, data = data_wider)\n\nsummary(lm_radiation_o3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = o3 ~ radiation, data = data_wider)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.012969 -0.004157 -0.000774  0.003937  0.019579 \n\nCoefficients:\n             Estimate Std. Error t value\n(Intercept) 0.0106526  0.0004495    23.7\nradiation   0.0002766  0.0000272    10.2\n                       Pr(>|t|)    \n(Intercept) <0.0000000000000002 ***\nradiation   <0.0000000000000002 ***\n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0057 on 719 degrees of freedom\nMultiple R-squared:  0.125,\tAdjusted R-squared:  0.124 \nF-statistic:  103 on 1 and 719 DF,  p-value: <0.0000000000000002\n```\n\n\n:::\n:::\n\n\n- With a p-value lower than .01, there is a statistically significant relationship between sunlight and o3. When sunlight is zero, the predicted o3 levels are 0.0107 ppm. For every additional unit increase in sunlight, o3 levels increase by 0.000277. This means that more sunlight is associated with more o3. \n- The R² value is .0125, suggesting that 12.5% of the variability of o3 is explained by sunlight. This means that there are other factors that contribute to the levels of o3 in the air besides sunlight. \n\n2. **Linear Modeling of Sunlight with NO2**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#radiation affect on no2\nlm_radiation_no2 <- lm(no2 ~ radiation, data = data_wider)\n\nsummary(lm_radiation_no2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = no2 ~ radiation, data = data_wider)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.00936 -0.00341 -0.00059  0.00299  0.01583 \n\nCoefficients:\n              Estimate Std. Error t value\n(Intercept)  0.0124012  0.0003533    35.1\nradiation   -0.0002207  0.0000216   -10.2\n                       Pr(>|t|)    \n(Intercept) <0.0000000000000002 ***\nradiation   <0.0000000000000002 ***\n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0045 on 708 degrees of freedom\n  (11 observations deleted due to missingness)\nMultiple R-squared:  0.128,\tAdjusted R-squared:  0.127 \nF-statistic:  104 on 1 and 708 DF,  p-value: <0.0000000000000002\n```\n\n\n:::\n:::\n\n\n- With a p-value lower than .01, there is a statistically significant relationship between sunlight and no2. When sunlight is zero, the predicted no2 levels are 0.0124ppm. For every additional unit of sunlight, no2 levels decrease by 0.000221ppm. This means that higher sunlight is associated with lower levels of no2. \n- The R² value is .0128, suggesting that 12.8% of the variability in no2 is explained by sunlight. This means that there are many other factors that contribute to the levels of so2 in the air besides sunlight.\n\nLinear modeling gives us more evidence that there is a relationship between sunlight and o3 and no2. More sunlight is associated with more o3 and less no2. Although it is not possible to conclude that sunlight is the primary cause for more production of o3 and the breakdown of no2, there is enough evidence to suggest that it is certainly a contributing factor.  \n\n### Permutation and Lineup Test \n\n**Lineup for Sunlight and O3**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(10)\n\n#radiation and o3\nggplot(lineup(null_permute('radiation'), data_wider), \n  aes(x=radiation, y=o3)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  theme(axis.text=element_blank(),\n        axis.title=element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/4_lineup_o3-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n#decrypt(\"4nZe kSDS Ec whQEDEhc V0\")\n```\n:::\n\n\n**Lineup for Sunlight and NO2**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#rainfall and no2\nggplot(lineup(null_permute('radiation'), data_wider), \n  aes(x=radiation, y=no2)) +\n  geom_point(alpha = 0.4) +\n  theme_minimal() +\n  facet_wrap(~ .sample) +\n  theme(axis.text=element_blank(),\n        axis.title=element_blank())\n```\n\n::: {.cell-output-display}\n![](report_part2_files/figure-html/4_lineup_no2-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n#decrypt(\"4nZe kSDS Ec whQEDEhc VV\")\n```\n:::\n\n\n- Finally, visual inference can be used to test if there is a relationship between sunlight and o3 and no2. This is done by permuting or shuffling the sunlight values and then plotting them with the o3 and no2 levels 19 times. \n- If the original scatter plot is identifiable next to the 19 null plots, then there is evidence that there is a relationship between the sunlight and the air pollutants.\n- When doing this test, both both o3 and no2 are identifiable. So, visual inference provides further evidence that there is relationship between sunlight and o3 and no2.\n\n### Conclusion for Relationship 4\n\nThere is evidence that sunlight helps produce more o3 but does not produce more no2. In fact, there is evidence that sunlight helps break down no2. When average sunlight and air pollution levels are plotted over time, we can see a general trend that as sunlight increases that o3 levels increase and and no2 levels decrease. This is further supported when sunlight and air pollutants are plotted in a scatter plot. Linear modeling shows a statistically significant positive relationship between sunlight and o3 and a negative relationship between sunlight and no2. Both o3 and no2 have 12% of their variability explained by sunlight. Finally, visual inference through the use of permutation and nullplots support that there is a relationship between sunlight and o3 and no2.\n\n### Generative AI analysis\n\nThe link to our use of ChatGPT for help on this project is:\n\n- Travis - https://chatgpt.com/share/672361c0-59a4-8006-b88a-60fa76c634ba\n- Pooja - https://chatgpt.com/share/67243b34-4210-8005-afd3-7317fe030407\n",
    "supporting": [
      "report_part2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}